/****** Object:  Table [dbo].[Facility]    Script Date: 01/09/2013 15:49:13 ******/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO

ALTER TABLE [dbo].[Facility] ALTER COLUMN PublicPhotoFileUri varchar(200);
GO

ALTER TABLE [dbo].[FacilityAudit] ALTER COLUMN PublicPhotoFileUri varchar(200);
GO

COMMIT