-- Add "pause account" functionality
-- If the flag is raised this client's listings will be excluded from search

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Client ADD
	AccountPaused bit NOT NULL CONSTRAINT DF_Client_AccountPaused DEFAULT 0
GO
ALTER TABLE dbo.Client SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.ClientAudit ADD
	AccountPaused bit NULL
GO
ALTER TABLE dbo.ClientAudit SET (LOCK_ESCALATION = TABLE)
GO

COMMIT