/*  Generated by CodeGen written by Concord Mfg.
 * Transform file used: BEException (v0.1.0.0).xslt
 * Date generated: 3/28/2012 12:46:03 PM
 * CodeGen version: 0.1.0.0  */

using System;

namespace ConcordMfg.PremierSeniorSolutions.WebService.BusinessEntities
{
	public class ClientAuditException : Exception
	{
		protected ClientAuditException()
			: this(null, null)
		{ }

		protected ClientAuditException(string message)
			: this(message, null)
		{ }

		public ClientAuditException(string message, ClientAudit clientAudit)
			: base(message)
		{
			this.ClientAudit = clientAudit;
		}

		public ClientAudit ClientAudit
		{
			get;
			set;
		}
	}

	public class ClientAuditNotFoundException : ClientAuditException
	{
		public ClientAuditNotFoundException(Guid clientAuditGuid)
			: base()
		{
			this.ClientAuditGuid = clientAuditGuid;
		}

		public override string Message
		{
			get
			{
				return string.Format("Could not find ClientAudit in the database with the following IDs: ClientAuditGuid:{0}.", ClientAuditGuid);
			}
		}

		public Guid ClientAuditGuid
		{
			get;
			set;
		}
	}

	public class ClientAuditAlreadyExistsException : ClientAuditException
	{
		public ClientAuditAlreadyExistsException(ClientAudit clientAudit)
			: base(null, clientAudit)
		{ }

		public override string Message
		{
			get
			{
				return string.Format("ClientAudit already exists in the database: {0}", ClientAudit.ToString());
			}
		}
	}
}
	