/*  Generated by CodeGen written by Concord Mfg.
 * Transform file used: BEException (v0.1.0.0).xslt
 * Date generated: 3/28/2012 12:46:03 PM
 * CodeGen version: 0.1.0.0  */

using System;

namespace ConcordMfg.PremierSeniorSolutions.WebService.BusinessEntities
{
	public class FacilityException : Exception
	{
		protected FacilityException()
			: this(null, null)
		{ }

		protected FacilityException(string message)
			: this(message, null)
		{ }

		public FacilityException(string message, Facility facility)
			: base(message)
		{
			this.Facility = facility;
		}

		public Facility Facility
		{
			get;
			set;
		}
	}

	public class FacilityNotFoundException : FacilityException
	{
		public FacilityNotFoundException(Guid facilityGuid)
			: base()
		{
			this.FacilityGuid = facilityGuid;
		}

		public override string Message
		{
			get
			{
				return string.Format("Could not find Facility in the database with the following IDs: FacilityGuid:{0}.", FacilityGuid);
			}
		}

		public Guid FacilityGuid
		{
			get;
			set;
		}
	}

	public class FacilityAlreadyExistsException : FacilityException
	{
		public FacilityAlreadyExistsException(Facility facility)
			: base(null, facility)
		{ }

		public override string Message
		{
			get
			{
				return string.Format("Facility already exists in the database: {0}", Facility.ToString());
			}
		}
	}
}
	