/*  Generated by CodeGen written by Concord Mfg.
 * Transform file used: BEException (v0.1.0.0).xslt
 * Date generated: 3/28/2012 12:46:03 PM
 * CodeGen version: 0.1.0.0  */

using System;

namespace ConcordMfg.PremierSeniorSolutions.WebService.BusinessEntities
{
	public class FacilityAuditException : Exception
	{
		protected FacilityAuditException()
			: this(null, null)
		{ }

		protected FacilityAuditException(string message)
			: this(message, null)
		{ }

		public FacilityAuditException(string message, FacilityAudit facilityAudit)
			: base(message)
		{
			this.FacilityAudit = facilityAudit;
		}

		public FacilityAudit FacilityAudit
		{
			get;
			set;
		}
	}

	public class FacilityAuditNotFoundException : FacilityAuditException
	{
		public FacilityAuditNotFoundException(Guid facilityAuditGuid)
			: base()
		{
			this.FacilityAuditGuid = facilityAuditGuid;
		}

		public override string Message
		{
			get
			{
				return string.Format("Could not find FacilityAudit in the database with the following IDs: FacilityAuditGuid:{0}.", FacilityAuditGuid);
			}
		}

		public Guid FacilityAuditGuid
		{
			get;
			set;
		}
	}

	public class FacilityAuditAlreadyExistsException : FacilityAuditException
	{
		public FacilityAuditAlreadyExistsException(FacilityAudit facilityAudit)
			: base(null, facilityAudit)
		{ }

		public override string Message
		{
			get
			{
				return string.Format("FacilityAudit already exists in the database: {0}", FacilityAudit.ToString());
			}
		}
	}
}
	