/*  Generated by CodeGen written by Concord Mfg.
 * Transform file used: BEException (v0.1.0.0).xslt
 * Date generated: 3/28/2012 12:46:03 PM
 * CodeGen version: 0.1.0.0  */

using System;

namespace ConcordMfg.PremierSeniorSolutions.WebService.BusinessEntities
{
	public class FacilityLocationCriteriaException : Exception
	{
		protected FacilityLocationCriteriaException()
			: this(null, null)
		{ }

		protected FacilityLocationCriteriaException(string message)
			: this(message, null)
		{ }

		protected FacilityLocationCriteriaException(string message, FacilityLocationCriteria facilityLocationCriteria)
			: base(message)
		{
			this.FacilityLocationCriteria = facilityLocationCriteria;
		}

		public FacilityLocationCriteria FacilityLocationCriteria
		{
			get;
			set;
		}
	}

	public class FacilityLocationCriteriaNotFoundException : FacilityLocationCriteriaException
	{
		public FacilityLocationCriteriaNotFoundException(Guid facilityGuid, Guid cityStateZipGuid)
			: base()
		{
			this.FacilityGuid = facilityGuid;
			this.CityStateZipGuid = cityStateZipGuid;
		}

		public override string Message
		{
			get
			{
				return string.Format("Could not find FacilityLocationCriteria in the database with the following IDs: FacilityGuid:{0}, CityStateZipGuid:{1}.", FacilityGuid, CityStateZipGuid);
			}
		}

		public Guid FacilityGuid
		{
			get;
			set;
		}

		public Guid CityStateZipGuid
		{
			get;
			set;
		}
	}

	public class FacilityLocationCriteriaAlreadyExistsException : FacilityLocationCriteriaException
	{
		public FacilityLocationCriteriaAlreadyExistsException(FacilityLocationCriteria facilityLocationCriteria)
			: base(null, facilityLocationCriteria)
		{ }

		public override string Message
		{
			get
			{
				return string.Format("FacilityLocationCriteria already exists in the database: {0}", FacilityLocationCriteria.ToString());
			}
		}
	}
}
	