/*  Generated by CodeGen written by Concord Mfg.
 * Transform file used: BEException (v0.1.0.0).xslt
 * Date generated: 3/28/2012 12:46:04 PM
 * CodeGen version: 0.1.0.0  */

using System;

namespace ConcordMfg.PremierSeniorSolutions.WebService.BusinessEntities
{
	public class OfferingException : Exception
	{
		protected OfferingException()
			: this(null, null)
		{ }

		protected OfferingException(string message)
			: this(message, null)
		{ }

		protected OfferingException(string message, Offering offering)
			: base(message)
		{
			this.Offering = offering;
		}

		public Offering Offering
		{
			get;
			set;
		}
	}

	public class OfferingNotFoundException : OfferingException
	{
		public OfferingNotFoundException(Guid offeringGuid)
			: base()
		{
			this.OfferingGuid = offeringGuid;
		}

		public override string Message
		{
			get
			{
				return string.Format("Could not find Offering in the database with the following IDs: OfferingGuid:{0}.", OfferingGuid);
			}
		}

		public Guid OfferingGuid
		{
			get;
			set;
		}
	}

	public class OfferingAlreadyExistsException : OfferingException
	{
		public OfferingAlreadyExistsException(Offering offering)
			: base(null, offering)
		{ }

		public override string Message
		{
			get
			{
				return string.Format("Offering already exists in the database: {0}", Offering.ToString());
			}
		}
	}
}
	