/*  Generated by CodeGen written by Concord Mfg
	*  Transform file used: AppCS (v0.1.0.0).xslt
	*  Date generated: 3/28/2012 12:46:34 PM
	*  CodeGen version: 0.1.0.0  */

using System;
using System.Windows;

namespace ConcordMfg.PremierSeniorSolutions.Silverlight3Client
{
	public partial class App : Application 
	{

		public App() 
		{
			this.Startup += this.OnStartup;
			this.Exit += this.OnExit;
			this.UnhandledException += this.Application_UnhandledException;


			InitializeComponent();
		}

		private void OnStartup(object sender, StartupEventArgs e) 
		{
			// Load the main control here
			this.RootVisual = new MainControl();
		}

		private void OnExit(object sender, EventArgs e) 
		{

		}
		
		private void Application_UnhandledException(object sender, ApplicationUnhandledExceptionEventArgs e)
		{
			if (!System.Diagnostics.Debugger.IsAttached)
			{
				e.Handled = true;

				try
				{
					string errorMsg = e.ExceptionObject.Message + @"\n" + e.ExceptionObject.StackTrace;
					errorMsg = errorMsg.Replace("\"", "\\\"").Replace("\r\n", @"\n");

					System.Windows.Browser.HtmlPage.Window.Eval("throw new Error(\"Unhandled Error in Silverlight 3 Application: " + errorMsg + "\");");
				}
				catch (Exception)
				{
				}
			}
		}
	}
}