/*  Generated by CodeGen written by Concord Mfg
	*  Transform file used: MainControlCS (v0.1.0.0).xslt
	*  Date generated: 3/28/2012 12:46:35 PM
	*  CodeGen version: 0.1.0.0  */

using System;
using System.Windows;

namespace ConcordMfg.PremierSeniorSolutions.Silverlight3Client
{
	public partial class MainControl : UserControl
	{
		public MainControl()
		{
			InitializeComponent();

			trvHeirarchy.SelectedItemChanged +=new System.Windows.RoutedPropertyChangedEventHandler<object>(trvHeirarchy_SelectedItemChanged);
		}

		private void trvHeirarchy_SelectedItemChanged(object sender, System.Windows.RoutedPropertyChangedEventArgs<object> e)
		{
			TreeViewItem selectedItem = e.NewValue as TreeViewItem;

			if (null == selectedItem.Tag) return;

			MainFrame.Navigate(new Uri(selectedItem.Tag as string, UriKind.Relative));
		}
	}
}