/*  Generated by CodeGen written by Concord Mfg.
 *  Transform file used: BEServiceReference (v0.1.0.0).xslt
 *  Date generated: 3/28/2012 12:46:19 PM
 *  CodeGen version: 0.1.0.0  */

using System;
using System.Runtime.Serialization;


namespace ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.DataContracts/2007/01")]
	[System.SerializableAttribute()]
	public partial class CityStateZip : object, System.Runtime.Serialization.IExtensibleDataObject
	{
		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
		
		private Guid _cityStateZipGuid = Guid.Empty;
		private string _city = null;
		private string _state = null;
		private string _zipCode = null;
		
		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}
		
		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 0)]
		public Guid CityStateZipGuid
		{
			get { return _cityStateZipGuid; }
			set { _cityStateZipGuid = value; }
		}
	
		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
		public string City
		{
			get { return _city; }
			set { _city = value; }
		}
	
		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
		public string State
		{
			get { return _state; }
			set { _state = value; }
		}
	
		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
		public string ZipCode
		{
			get { return _zipCode; }
			set { _zipCode = value; }
		}
	
	}
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.FaultContracts/2007/01")]
	[System.SerializableAttribute()]
	public partial class CityStateZipFault : object, System.Runtime.Serialization.IExtensibleDataObject
	{
		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
		private string _errorMessage;
		
		private Guid _cityStateZipGuid = Guid.Empty;
		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}
		
		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public string ErrorMessage
		{
			get
			{
				return this._errorMessage;
			}
			set
			{
				this._errorMessage = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public Guid CityStateZipGuid
		{
			get { return _cityStateZipGuid; }
			set { _cityStateZipGuid = value; }
		}
	
	}
	

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.DataContracts/2007/01")]
	[System.SerializableAttribute()]
	public partial class DefaultFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject
	{
		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private int ErrorIdField;

		private string ErrorMessageField;

		private System.Guid CorrelationIdField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public int ErrorId
		{
			get
			{
				return this.ErrorIdField;
			}
			set
			{
				this.ErrorIdField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public string ErrorMessage
		{
			get
			{
				return this.ErrorMessageField;
			}
			set
			{
				this.ErrorMessageField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
		public System.Guid CorrelationId
		{
			get
			{
				return this.CorrelationIdField;
			}
			set
			{
				this.CorrelationIdField = value;
			}
		}
	}
	

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.FaultContracts/2007/01")]
	[System.SerializableAttribute()]
	public partial class FacilityFault : object, System.Runtime.Serialization.IExtensibleDataObject
	{
		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
		private string _errorMessage;
		
		private Guid _facilityGuid = Guid.Empty;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public string ErrorMessage
		{
			get
			{
				return this._errorMessage;
			}
			set
			{
				this._errorMessage = value;
			}
		}


		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public Guid FacilityGuid
		{
			get { return _facilityGuid; }
			set { _facilityGuid = value; }
		}
	
	}


	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.ServiceContractAttribute(Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01", ConfigurationName = "ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.ICityStateZip")]
	public interface ICityStateZip
	{
		[System.ServiceModel.OperationContractAttribute(Action = "GetCityStateZipByCityStateZipGuid",
			ReplyAction = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/ICityStateZip/GetCityStateZipByCityStateZipGuidResponse")]
		[System.ServiceModel.FaultContractAttribute(typeof(ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.CityStateZipFault),
			Action = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/ICityStateZip/GetCityStateZipByCityStateZipGuidCityStateZipFault",
			Name = "CityStateZipFault", Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.FaultContracts/2007/01")]
		ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.CityStateZip GetCityStateZipByCityStateZipGuid(Guid cityStateZipGuid);

		[System.ServiceModel.OperationContractAttribute(Action = "GetAllCityStateZip",
			ReplyAction = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/ICityStateZip/GetAllCityStateZipResponse")]
		[System.ServiceModel.FaultContractAttribute(typeof(ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.DefaultFaultContract),
			Action = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/ICityStateZip/GetAllCityStateZipDefaultFaultContract",
			Name = "DefaultFaultContract", Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.DataContracts/2007/01")]
		ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.CityStateZip[] GetAllCityStateZip();

		[System.ServiceModel.OperationContractAttribute(Action = "InsertCityStateZip",
			ReplyAction = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/ICityStateZip/InsertCityStateZipResponse")]
		[System.ServiceModel.FaultContractAttribute(typeof(ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.DefaultFaultContract),
			Action = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/ICityStateZip/InsertCityStateZipDefaultFaultContract",
			Name = "DefaultFaultContract", Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.DataContracts/2007/01")]
		void InsertCityStateZip(ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.CityStateZip cityStateZip);

		[System.ServiceModel.OperationContractAttribute(Action = "DeleteCityStateZip",
			ReplyAction = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/ICityStateZip/DeleteCityStateZipResponse")]
		[System.ServiceModel.FaultContractAttribute(typeof(ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.DefaultFaultContract),
			Action = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/ICityStateZip/DeleteCityStateZipDefaultFaultContract",
			Name = "DefaultFaultContract", Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.DataContracts/2007/01")]
		void DeleteCityStateZip(ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.CityStateZip cityStateZip);

		[System.ServiceModel.OperationContractAttribute(Action = "UpdateCityStateZip",
			ReplyAction = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/ICityStateZip/UpdateCityStateZipResponse")]
		[System.ServiceModel.FaultContractAttribute(typeof(ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.DefaultFaultContract),
			Action = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/ICityStateZip/UpdateCityStateZipDefaultFaultContract",
			Name = "DefaultFaultContract", Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.DataContracts/2007/01")]
		void UpdateCityStateZip(ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.CityStateZip cityStateZip);

		[System.ServiceModel.OperationContractAttribute(Action = "GetCityStateZipsForFacility",
			ReplyAction = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/ICityStateZip/GetCityStateZipsForFacilityResponse")]
		[System.ServiceModel.FaultContractAttribute(typeof(ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.FacilityFault),
			Action = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/ICityStateZip/GetCityStateZipsForFacilityFacilityFault",
			Name = "FacilityFault", Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.FaultContracts/2007/01")]
		ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.CityStateZip[] GetCityStateZipsForFacility(Guid facilityGuid);

		[System.ServiceModel.OperationContractAttribute(Action = "GetCityStateZipsNotForFacility",
			ReplyAction = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/ICityStateZip/GetCityStateZipsNotForFacilityResponse")]
		[System.ServiceModel.FaultContractAttribute(typeof(ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.FacilityFault),
			Action = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/ICityStateZip/GetCityStateZipsNotForFacilityFacilityFault",
			Name = "FacilityFault", Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.FaultContracts/2007/01")]
		ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.CityStateZip[] GetCityStateZipsNotForFacility(Guid facilityGuid);

		[System.ServiceModel.OperationContractAttribute(Action = "AddFacilityToCityStateZip",
			ReplyAction = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/ICityStateZip/AddFacilityToCityStateZipResponse")]
		[System.ServiceModel.FaultContractAttribute(typeof(ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.FacilityLocationCriteriaFault),
			Action = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/ICityStateZip/AddFacilityToCityStateZipFacilityLocationCriteriaFault",
			Name = "FacilityLocationCriteriaFault", Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.FaultContracts/2007/01")]
		void AddFacilityToCityStateZip(Guid cityStateZipGuid, Guid facilityGuid);

		[System.ServiceModel.OperationContractAttribute(Action = "DeleteFacilityFromCityStateZip",
			ReplyAction = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/ICityStateZip/DeleteFacilityFromCityStateZipResponse")]
		[System.ServiceModel.FaultContractAttribute(typeof(ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.FacilityLocationCriteriaFault),
			Action = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/ICityStateZip/DeleteFacilityFromCityStateZipFacilityLocationCriteriaFault",
			Name = "FacilityLocationCriteriaFault", Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.FaultContracts/2007/01")]
		void DeleteFacilityFromCityStateZip(Guid cityStateZipGuid, Guid facilityGuid);

	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	public interface ICityStateZipChannel : ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.ICityStateZip, System.ServiceModel.IClientChannel
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	public partial class CityStateZipClient : System.ServiceModel.ClientBase<ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.ICityStateZip>, ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.ICityStateZip
	{
		public CityStateZipClient()
		{
		}

		public CityStateZipClient(string endpointConfigurationName)
			: base(endpointConfigurationName)
		{
		}

		public CityStateZipClient(string endpointConfigurationName, string remoteAddress)
			: base(endpointConfigurationName, remoteAddress)
		{
		}

		public CityStateZipClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
			: base(endpointConfigurationName, remoteAddress)
		{
		}

		public CityStateZipClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
			: base(binding, remoteAddress)
		{
		}

		public ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.CityStateZip GetCityStateZipByCityStateZipGuid(Guid cityStateZipGuid)
		{
			return base.Channel.GetCityStateZipByCityStateZipGuid(cityStateZipGuid);
		}

		public ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.CityStateZip[] GetAllCityStateZip()
		{
			return base.Channel.GetAllCityStateZip();
		}

		public void InsertCityStateZip(ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.CityStateZip cityStateZip)
		{
			base.Channel.InsertCityStateZip(cityStateZip);
		}

		public void DeleteCityStateZip(ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.CityStateZip cityStateZip)
		{
			base.Channel.DeleteCityStateZip(cityStateZip);
		}

		public void UpdateCityStateZip(ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.CityStateZip cityStateZip)
		{
			base.Channel.UpdateCityStateZip(cityStateZip);
		}

		public ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.CityStateZip[] GetCityStateZipsForFacility(Guid facilityGuid)
		{
			return base.Channel.GetCityStateZipsForFacility(facilityGuid);
		}

		public ConcordMfg.PremierSeniorSolutions.WebService.Client.CityStateZipSvc.CityStateZip[] GetCityStateZipsNotForFacility(Guid facilityGuid)
		{
			return base.Channel.GetCityStateZipsNotForFacility(facilityGuid);
		}

		public void AddFacilityToCityStateZip(Guid cityStateZipGuid, Guid facilityGuid)
		{
			base.Channel.AddFacilityToCityStateZip(cityStateZipGuid, facilityGuid);
		}

		public void DeleteFacilityFromCityStateZip(Guid cityStateZipGuid, Guid facilityGuid)
		{
			base.Channel.DeleteFacilityFromCityStateZip(cityStateZipGuid, facilityGuid);
		}

	}
}
	