/*  Generated by CodeGen written by Concord Mfg.
 *  Transform file used: BEServiceReference (v0.1.0.0).xslt
 *  Date generated: 3/28/2012 12:46:19 PM
 *  CodeGen version: 0.1.0.0  */

using System;
using System.Runtime.Serialization;


namespace ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.DataContracts/2007/01")]
	[System.SerializableAttribute()]
	public partial class PaymentInfoAudit : object, System.Runtime.Serialization.IExtensibleDataObject
	{
		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
		
		private Guid _paymentInfoAuditGuid = Guid.Empty;
		private Guid _paymentInfoGuid = Guid.Empty;
		private int _paymentInfoID = 0;
		private string _amazonToken = null;
		private DateTime _dateModified = default(DateTime);
		
		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}
		
		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 0)]
		public Guid PaymentInfoAuditGuid
		{
			get { return _paymentInfoAuditGuid; }
			set { _paymentInfoAuditGuid = value; }
		}
	
		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
		public Guid PaymentInfoGuid
		{
			get { return _paymentInfoGuid; }
			set { _paymentInfoGuid = value; }
		}
	
		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
		public int PaymentInfoID
		{
			get { return _paymentInfoID; }
			set { _paymentInfoID = value; }
		}
	
		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
		public string AmazonToken
		{
			get { return _amazonToken; }
			set { _amazonToken = value; }
		}
	
		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
		public DateTime DateModified
		{
			get { return _dateModified; }
			set { _dateModified = value; }
		}
	
	}
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.FaultContracts/2007/01")]
	[System.SerializableAttribute()]
	public partial class PaymentInfoAuditFault : object, System.Runtime.Serialization.IExtensibleDataObject
	{
		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
		private string _errorMessage;
		
		private Guid _paymentInfoAuditGuid = Guid.Empty;
		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}
		
		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public string ErrorMessage
		{
			get
			{
				return this._errorMessage;
			}
			set
			{
				this._errorMessage = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public Guid PaymentInfoAuditGuid
		{
			get { return _paymentInfoAuditGuid; }
			set { _paymentInfoAuditGuid = value; }
		}
	
	}
	

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.DataContracts/2007/01")]
	[System.SerializableAttribute()]
	public partial class DefaultFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject
	{
		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private int ErrorIdField;

		private string ErrorMessageField;

		private System.Guid CorrelationIdField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public int ErrorId
		{
			get
			{
				return this.ErrorIdField;
			}
			set
			{
				this.ErrorIdField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public string ErrorMessage
		{
			get
			{
				return this.ErrorMessageField;
			}
			set
			{
				this.ErrorMessageField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
		public System.Guid CorrelationId
		{
			get
			{
				return this.CorrelationIdField;
			}
			set
			{
				this.CorrelationIdField = value;
			}
		}
	}
	


	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.ServiceContractAttribute(Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01", ConfigurationName = "ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.IPaymentInfoAudit")]
	public interface IPaymentInfoAudit
	{
		[System.ServiceModel.OperationContractAttribute(Action = "GetPaymentInfoAuditByPaymentInfoAuditGuid",
			ReplyAction = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/IPaymentInfoAudit/GetPaymentInfoAuditByPaymentInfoAuditGuidResponse")]
		[System.ServiceModel.FaultContractAttribute(typeof(ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.PaymentInfoAuditFault),
			Action = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/IPaymentInfoAudit/GetPaymentInfoAuditByPaymentInfoAuditGuidPaymentInfoAuditFault",
			Name = "PaymentInfoAuditFault", Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.FaultContracts/2007/01")]
		ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.PaymentInfoAudit GetPaymentInfoAuditByPaymentInfoAuditGuid(Guid paymentInfoAuditGuid);

		[System.ServiceModel.OperationContractAttribute(Action = "GetAllPaymentInfoAudit",
			ReplyAction = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/IPaymentInfoAudit/GetAllPaymentInfoAuditResponse")]
		[System.ServiceModel.FaultContractAttribute(typeof(ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.DefaultFaultContract),
			Action = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/IPaymentInfoAudit/GetAllPaymentInfoAuditDefaultFaultContract",
			Name = "DefaultFaultContract", Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.DataContracts/2007/01")]
		ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.PaymentInfoAudit[] GetAllPaymentInfoAudit();

		[System.ServiceModel.OperationContractAttribute(Action = "InsertPaymentInfoAudit",
			ReplyAction = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/IPaymentInfoAudit/InsertPaymentInfoAuditResponse")]
		[System.ServiceModel.FaultContractAttribute(typeof(ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.DefaultFaultContract),
			Action = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/IPaymentInfoAudit/InsertPaymentInfoAuditDefaultFaultContract",
			Name = "DefaultFaultContract", Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.DataContracts/2007/01")]
		void InsertPaymentInfoAudit(ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.PaymentInfoAudit paymentInfoAudit);

		[System.ServiceModel.OperationContractAttribute(Action = "DeletePaymentInfoAudit",
			ReplyAction = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/IPaymentInfoAudit/DeletePaymentInfoAuditResponse")]
		[System.ServiceModel.FaultContractAttribute(typeof(ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.DefaultFaultContract),
			Action = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/IPaymentInfoAudit/DeletePaymentInfoAuditDefaultFaultContract",
			Name = "DefaultFaultContract", Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.DataContracts/2007/01")]
		void DeletePaymentInfoAudit(ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.PaymentInfoAudit paymentInfoAudit);

		[System.ServiceModel.OperationContractAttribute(Action = "UpdatePaymentInfoAudit",
			ReplyAction = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/IPaymentInfoAudit/UpdatePaymentInfoAuditResponse")]
		[System.ServiceModel.FaultContractAttribute(typeof(ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.DefaultFaultContract),
			Action = "http://ConcordMfg.PremierSeniorSolutions.WebService.ServiceContracts/2007/01/IPaymentInfoAudit/UpdatePaymentInfoAuditDefaultFaultContract",
			Name = "DefaultFaultContract", Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.DataContracts/2007/01")]
		void UpdatePaymentInfoAudit(ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.PaymentInfoAudit paymentInfoAudit);

	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	public interface IPaymentInfoAuditChannel : ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.IPaymentInfoAudit, System.ServiceModel.IClientChannel
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	public partial class PaymentInfoAuditClient : System.ServiceModel.ClientBase<ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.IPaymentInfoAudit>, ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.IPaymentInfoAudit
	{
		public PaymentInfoAuditClient()
		{
		}

		public PaymentInfoAuditClient(string endpointConfigurationName)
			: base(endpointConfigurationName)
		{
		}

		public PaymentInfoAuditClient(string endpointConfigurationName, string remoteAddress)
			: base(endpointConfigurationName, remoteAddress)
		{
		}

		public PaymentInfoAuditClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
			: base(endpointConfigurationName, remoteAddress)
		{
		}

		public PaymentInfoAuditClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
			: base(binding, remoteAddress)
		{
		}

		public ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.PaymentInfoAudit GetPaymentInfoAuditByPaymentInfoAuditGuid(Guid paymentInfoAuditGuid)
		{
			return base.Channel.GetPaymentInfoAuditByPaymentInfoAuditGuid(paymentInfoAuditGuid);
		}

		public ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.PaymentInfoAudit[] GetAllPaymentInfoAudit()
		{
			return base.Channel.GetAllPaymentInfoAudit();
		}

		public void InsertPaymentInfoAudit(ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.PaymentInfoAudit paymentInfoAudit)
		{
			base.Channel.InsertPaymentInfoAudit(paymentInfoAudit);
		}

		public void DeletePaymentInfoAudit(ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.PaymentInfoAudit paymentInfoAudit)
		{
			base.Channel.DeletePaymentInfoAudit(paymentInfoAudit);
		}

		public void UpdatePaymentInfoAudit(ConcordMfg.PremierSeniorSolutions.WebService.Client.PaymentInfoAuditSvc.PaymentInfoAudit paymentInfoAudit)
		{
			base.Channel.UpdatePaymentInfoAudit(paymentInfoAudit);
		}

	}
}
	