/*	Generated by CodeGen written by Concord Mfg
 *  Transform file used: BEViewModel (v0.1.0.0).xslt
 *  Date generated: 3/28/2012 12:46:36 PM
 *  CodeGen version: 0.1.0.0  */

using System;
using System.Collections.Generic;
using ConcordMfg.PremierSeniorSolutions.Client.Models;


namespace ConcordMfg.PremierSeniorSolutions.Client.ViewModels
{
	/// <summary>
	/// View Model for FacilityPhoto (FacilityPhoto).
	/// </summary>
	public class FacilityPhotoViewModel : NotifyPropertyChangedBaseWithOwner
	{
		#region Private Fields
		protected Guid _facilityPhotoGuid = Guid.Empty;
		protected string _photoUri = null;
		protected Guid _facilityGuid = Guid.Empty;

		private string _facilityGuid_Facility_FacilityName = null;

		private FacilityViewModel _facilityGuid_Facility = null;
		#endregion


		#region Constructors
		public FacilityPhotoViewModel()
		{
		}

		public FacilityPhotoViewModel(Guid facilityPhotoGuid, string photoUri, Guid facilityGuid)
		{
			this.FacilityPhotoGuid = facilityPhotoGuid;
			this.PhotoUri = photoUri;
			this.FacilityGuid = facilityGuid;
		}
		#endregion


		#region Private GetAndSet Methods

		private void GetAndSetFacilityGuid_Facility(Guid facilityGuid)
		{
			if (Guid.Empty != facilityGuid &&
				(null == _facilityGuid_Facility || _facilityGuid_Facility.FacilityGuid != facilityGuid))
			{
				try
				{
					this.FacilityGuid_Facility = DataAccess.GetFacility(facilityGuid);
					this.FacilityGuid_Facility_FacilityName = _facilityGuid_Facility.FacilityName;
				}
				catch (Exception ex)
				{
					throw ex;
				}
			}
		}
		#endregion


		#region Public Properties

		public Guid FacilityPhotoGuid
		{
			get { return _facilityPhotoGuid; }
			set
			{
				_facilityPhotoGuid = value;
				RaisePropertyChanged("FacilityPhotoGuid");
			}
		}

		public string PhotoUri
		{
			get { return _photoUri; }
			set
			{
				_photoUri = value;
				RaisePropertyChanged("PhotoUri");
			}
		}

		public Guid FacilityGuid
		{
			get { return _facilityGuid; }
			set
			{
				_facilityGuid = value;
				RaisePropertyChanged("FacilityGuid");
				this.GetAndSetFacilityGuid_Facility(value);
			}
		}

		public string FacilityGuid_Facility_FacilityName
		{
			get
			{ return _facilityGuid_Facility_FacilityName; }
			set
			{
				if (Guid.Empty != value)
				{
					_facilityGuid_Facility_FacilityName = value;
					RaisePropertyChanged("FacilityGuid_Facility_FacilityName");
				}
			}
		}

		/// <summary>
		/// Gets and sets Facility related through FacilityGuid.
		/// </summary>
		public FacilityViewModel FacilityGuid_Facility
		{
			get
			{
				if (Guid.Empty != _facilityGuid && null == _facilityGuid_Facility)
				{ this.GetAndSetFacilityGuid_Facility(_facilityGuid); }
				return _facilityGuid_Facility;
			}
			set
			{
				if (Guid.Empty != value)
				{
					_facilityGuid_Facility = value;
					RaisePropertyChanged("FacilityGuid_Facility");
				}
			}
		}

		public string FacilityGuidPDC
		{
			get
			{
				if (null == this.FacilityGuid_Facility || this.FacilityGuid == Guid.Empty)
					return "*Unassigned*";
				return this.FacilityGuid_Facility.PDC;
			}
			set { ; }
		}

		public string PDC
		{
			get { return this.ToString(); }
			set { ; }
		}
		#endregion


		#region Overrides
		public override string ToString()
		{
			return PhotoUri;
		}
		#endregion
	}
}