/*	Generated by CodeGen written by Concord Mfg
 *  Transform file used: BEViewModel (v0.1.0.0).xslt
 *  Date generated: 3/28/2012 12:46:36 PM
 *  CodeGen version: 0.1.0.0  */

using System;
using System.Collections.Generic;
using ConcordMfg.PremierSeniorSolutions.Client.Models;


namespace ConcordMfg.PremierSeniorSolutions.Client.ViewModels
{
	/// <summary>
	/// View Model for Facility Offering (FacilityOffering).
	/// </summary>
	public class FacilityOfferingViewModel : NotifyPropertyChangedBaseWithOwner
	{
		#region Private Fields
		protected Guid _facilityGuid = Guid.Empty;
		protected Guid _offeringGuid = Guid.Empty;
		protected bool _isChecked = false;


		#endregion


		#region Constructors
		public FacilityOfferingViewModel()
		{
		}

		public FacilityOfferingViewModel(Guid facilityGuid, Guid offeringGuid, bool isChecked)
		{
			this.FacilityGuid = facilityGuid;
			this.OfferingGuid = offeringGuid;
			this.IsChecked = isChecked;
		}
		#endregion


		#region Private GetAndSet Methods

		private void GetAndSetFacilityGuid_Facility(Guid facilityGuid)
		{
			if (Guid.Empty != facilityGuid &&
				(null == _facilityGuid_Facility || _facilityGuid_Facility.FacilityGuid != facilityGuid))
			{
				try
				{
					this.FacilityGuid_Facility = DataAccess.GetFacility(facilityGuid);
					this.FacilityGuid_Facility_FacilityName = _facilityGuid_Facility.FacilityName;
				}
				catch (Exception ex)
				{
					throw ex;
				}
			}
		}

		private void GetAndSetOfferingGuid_Offering(Guid offeringGuid)
		{
			if (Guid.Empty != offeringGuid &&
				(null == _offeringGuid_Offering || _offeringGuid_Offering.OfferingGuid != offeringGuid))
			{
				try
				{
					this.OfferingGuid_Offering = DataAccess.GetOffering(offeringGuid);
					this.OfferingGuid_Offering_OfferingName = _offeringGuid_Offering.OfferingName;
				}
				catch (Exception ex)
				{
					throw ex;
				}
			}
		}
		#endregion


		#region Public Properties

		public Guid FacilityGuid
		{
			get { return _facilityGuid; }
			set
			{
				_facilityGuid = value;
				RaisePropertyChanged("FacilityGuid");
			}
		}

		public Guid OfferingGuid
		{
			get { return _offeringGuid; }
			set
			{
				_offeringGuid = value;
				RaisePropertyChanged("OfferingGuid");
			}
		}

		public bool IsChecked
		{
			get { return _isChecked; }
			set
			{
				_isChecked = value;
				RaisePropertyChanged("IsChecked");
			}
		}

		public string PDC
		{
			get { return this.ToString(); }
			set { ; }
		}
		#endregion


		#region Overrides
		public override string ToString()
		{
			return FacilityGuid.ToString();
		}
		#endregion
	}
}