/*	Generated by CodeGen written by Concord Mfg
 *  Transform file used: BEViewModel (v0.1.0.0).xslt
 *  Date generated: 3/28/2012 12:46:36 PM
 *  CodeGen version: 0.1.0.0  */

using System;
using System.Collections.Generic;
using ConcordMfg.PremierSeniorSolutions.Client.Models;


namespace ConcordMfg.PremierSeniorSolutions.Client.ViewModels
{
	/// <summary>
	/// View Model for Listing Type (ListingType).
	/// </summary>
	public class ListingTypeViewModel : NotifyPropertyChangedBaseWithOwner
	{
		#region Private Fields
		protected Guid _listingTypeGuid = Guid.Empty;
		protected string _listingTypeName = null;


		#endregion


		#region Constructors
		public ListingTypeViewModel()
		{
		}

		public ListingTypeViewModel(Guid listingTypeGuid, string listingTypeName)
		{
			this.ListingTypeGuid = listingTypeGuid;
			this.ListingTypeName = listingTypeName;
		}
		#endregion


		#region Private GetAndSet Methods
		#endregion


		#region Public Properties

		public Guid ListingTypeGuid
		{
			get { return _listingTypeGuid; }
			set
			{
				_listingTypeGuid = value;
				RaisePropertyChanged("ListingTypeGuid");
			}
		}

		public string ListingTypeName
		{
			get { return _listingTypeName; }
			set
			{
				_listingTypeName = value;
				RaisePropertyChanged("ListingTypeName");
			}
		}

		public string PDC
		{
			get { return this.ToString(); }
			set { ; }
		}
		#endregion


		#region Overrides
		public override string ToString()
		{
			return ListingTypeName;
		}
		#endregion
	}
}