/*  Generated by CodeGen written by Concord Mfg
	*  Transform file used: BEMasterDetailViewCS (v0.1.0.0).xslt
	*  Date generated: 3/28/2012 12:46:36 PM
	*  CodeGen version: 0.1.0.0  */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Shapes;
using System.Windows.Navigation;

namespace ConcordMfg.PremierSeniorSolutions.Silverlight3Client.Views
{
	public partial class OfferingMasterDetailView : Page
	{
		public OfferingMasterDetailView()
		{
			InitializeComponent();

			this.OfferingListBox.SelectionChanged += new SelectionChangedEventHandler(OfferingListBox_SelectionChanged);
		}

		void OfferingListBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
		{
			OfferingViewModel currentOffering = this.OfferingListBox.SelectedItem as OfferingViewModel;

		}

		// Executes when the user navigates to this page.
		protected override void OnNavigatedTo(NavigationEventArgs e)
		{
		}
	}
	
}