/*  Generated by CodeGen written by Concord Mfg.
 * Transform file used: JoinDataAccess (v0.1.0.0).xslt
 * Date generated: 3/28/2012 12:46:18 PM
 * CodeGen version: 0.1.0.0  */

using System;
using System.ComponentModel;
using ConcordMfg.PremierSeniorSolutions.Client.Tools;

namespace ConcordMfg.PremierSeniorSolutions.Client.ViewModels
{
	/// <summary>
	/// Access the data for the FacilityWithOffering class.
	/// </summary>
	// [DataObject]
	public partial class DataAccess
	{
		#region Private Fields
		private static ConcordMfg.PremierSeniorSolutions.WebService.Client.FacilityWithOfferingSvc.FacilityWithOfferingClient
			_facilityWithOfferingClient = new ConcordMfg.PremierSeniorSolutions.WebService.Client.FacilityWithOfferingSvc.FacilityWithOfferingClient();
		#endregion


		#region Public Methods
		/// <summary>
		/// Retrieves FacilityWithOffering from the web service.
		/// </summary>
		/// <returns>A Collection of all FacilityWithOffering.</returns>
		[DataObjectMethodAttribute(DataObjectMethodType.Select, true)]
		public static FacilityWithOfferingCollection GetFacilityWithOffering()
		{
			ConcordMfg.PremierSeniorSolutions.WebService.Client.FacilityWithOfferingSvc.FacilityWithOffering[] facilitiesWithOffering =
				_facilityWithOfferingClient.GetAllFacilityWithOffering();
			FacilityWithOfferingCollection result = new FacilityWithOfferingCollection(
				facilitiesWithOffering.ToViewModels());
			return result;
		}

		/*
		/// <summary>
		/// Retrieves a FacilityWithOffering Collection from the web service.
		/// </summary>
		/// <param name="facilityGuid">Facility Guid</param>
		/// <returns>A Collection of FacilityWithOffering.</returns>
		[DataObjectMethodAttribute(DataObjectMethodType.Select, false)]
		public static FacilityWithOfferingCollection GetFacilitiesWithOfferingForFacility(Guid facilityGuid)
		{
			ConcordMfg.PremierSeniorSolutions.WebService.Client.FacilityWithOfferingSvc.FacilityWithOffering[] facilitiesWithOffering =
				_facilityWithOfferingClient.GetFacilityWithOfferingByFacilityGuid(facilityGuid);
			FacilityWithOfferingCollection result = new FacilityWithOfferingCollection(
				facilitiesWithOffering.ToViewModels());
			return result;
		}
		*/

		/// <summary>
		/// Retrieves a FacilityWithOffering Collection from the web service.
		/// </summary>
		/// <param name="offeringGuid">Offering Guid</param>
		/// <returns>A Collection of FacilityWithOffering.</returns>
		[DataObjectMethodAttribute(DataObjectMethodType.Select, false)]
		public static FacilityWithOfferingCollection GetFacilitiesWithOfferingForOffering(Guid offeringGuid)
		{
			ConcordMfg.PremierSeniorSolutions.WebService.Client.FacilityWithOfferingSvc.FacilityWithOffering[] facilitiesWithOffering =
				_facilityWithOfferingClient.GetFacilityWithOfferingByOfferingGuid(offeringGuid);
			FacilityWithOfferingCollection result = new FacilityWithOfferingCollection(
				facilitiesWithOffering.ToViewModels());
			return result;
		}

		
		#endregion
	}
}