/*  Generated by CodeGen written by Concord Mfg.
 * Transform file used: JoinDataAccess (v0.1.0.0).xslt
 * Date generated: 3/28/2012 12:46:18 PM
 * CodeGen version: 0.1.0.0  */

using System;
using System.ComponentModel;
using ConcordMfg.PremierSeniorSolutions.Client.Tools;

namespace ConcordMfg.PremierSeniorSolutions.Client.ViewModels
{
	/// <summary>
	/// Access the data for the FacilityWithCityStateZip class.
	/// </summary>
	// [DataObject]
	public partial class DataAccess
	{
		#region Private Fields
		private static ConcordMfg.PremierSeniorSolutions.WebService.Client.FacilityWithCityStateZipSvc.FacilityWithCityStateZipClient
			_facilityWithCityStateZipClient = new ConcordMfg.PremierSeniorSolutions.WebService.Client.FacilityWithCityStateZipSvc.FacilityWithCityStateZipClient();
		#endregion


		#region Public Methods
		/// <summary>
		/// Retrieves FacilityWithCityStateZip from the web service.
		/// </summary>
		/// <returns>A Collection of all FacilityWithCityStateZip.</returns>
		[DataObjectMethodAttribute(DataObjectMethodType.Select, true)]
		public static FacilityWithCityStateZipCollection GetFacilityWithCityStateZip()
		{
			ConcordMfg.PremierSeniorSolutions.WebService.Client.FacilityWithCityStateZipSvc.FacilityWithCityStateZip[] facilitiesWithCityStateZip =
				_facilityWithCityStateZipClient.GetAllFacilityWithCityStateZip();
			FacilityWithCityStateZipCollection result = new FacilityWithCityStateZipCollection(
				facilitiesWithCityStateZip.ToViewModels());
			return result;
		}

		/*
		/// <summary>
		/// Retrieves a FacilityWithCityStateZip Collection from the web service.
		/// </summary>
		/// <param name="facilityGuid">Facility Guid</param>
		/// <returns>A Collection of FacilityWithCityStateZip.</returns>
		[DataObjectMethodAttribute(DataObjectMethodType.Select, false)]
		public static FacilityWithCityStateZipCollection GetFacilitiesWithCityStateZipForFacility(Guid facilityGuid)
		{
			ConcordMfg.PremierSeniorSolutions.WebService.Client.FacilityWithCityStateZipSvc.FacilityWithCityStateZip[] facilitiesWithCityStateZip =
				_facilityWithCityStateZipClient.GetFacilityWithCityStateZipByFacilityGuid(facilityGuid);
			FacilityWithCityStateZipCollection result = new FacilityWithCityStateZipCollection(
				facilitiesWithCityStateZip.ToViewModels());
			return result;
		}
		*/

		/// <summary>
		/// Retrieves a FacilityWithCityStateZip Collection from the web service.
		/// </summary>
		/// <param name="cityStateZipGuid">City State Zip Guid</param>
		/// <returns>A Collection of FacilityWithCityStateZip.</returns>
		[DataObjectMethodAttribute(DataObjectMethodType.Select, false)]
		public static FacilityWithCityStateZipCollection GetFacilitiesWithCityStateZipForCityStateZip(Guid cityStateZipGuid)
		{
			ConcordMfg.PremierSeniorSolutions.WebService.Client.FacilityWithCityStateZipSvc.FacilityWithCityStateZip[] facilitiesWithCityStateZip =
				_facilityWithCityStateZipClient.GetFacilityWithCityStateZipByCityStateZipGuid(cityStateZipGuid);
			FacilityWithCityStateZipCollection result = new FacilityWithCityStateZipCollection(
				facilitiesWithCityStateZip.ToViewModels());
			return result;
		}

		
		#endregion
	}
}