/*  Generated by CodeGen written by Concord Mfg.
 *  Transform file used: BEGridControl (v0.1.0.0).xslt
 *  Date generated: 3/28/2012 12:46:29 PM
 *  CodeGen version: 0.1.0.0  */

using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using ISWG = ISNet.WebUI.WebGrid;

public partial class PaymentInfoAudit_Controls_PaymentInfoAuditGrid : System.Web.UI.UserControl
{
	private bool _needsRefresh = false;

	protected void Page_Load(object sender, EventArgs e)
	{
		wgPaymentInfoAudit.InitializePostBack += new ISWG.PostBackEventHandler(wgPaymentInfoAudit_InitializePostBack);
		wgPaymentInfoAudit.Unload += new EventHandler(wgPaymentInfoAudit_Unload);
	}

	void wgPaymentInfoAudit_InitializePostBack(object sender, ISWG.PostbackEventArgs e)
	{
		if (wgPaymentInfoAudit.ActionName == "AddRow")
		{
			_needsRefresh = true;
		}
	}

	void wgPaymentInfoAudit_Unload(object sender, EventArgs e)
	{
		if (_needsRefresh)
		{
			_needsRefresh = false;

			//isdPaymentInfoAudit.DataBind();
			//isdPaymentInfoAudit.DoSelect();
			//isdPaymentInfoAudit.Select();

			//wgPaymentInfoAudit.DataBind();
			//wgPaymentInfoAudit.GetChanges();
			//wgPaymentInfoAudit.RebindDataSource();
			//wgPaymentInfoAudit.Reset();

			// This is the current working solution. Hopefully one of the above will work instead.
			// Comment this line out to debug. The refresh hides error messages.
			this.Response.Redirect("~/PaymentInfoAudit/PaymentInfoAuditGrid.aspx");
		}
	}

	/// <summary>
	/// Builds to the link button to send the PaymentInfoAuditGuid link to the PaymentInfoAuditDetail page in the same folder.
	/// </summary>
	/// <param name="sender">Sender, as object.</param>
	/// <param name="e">Intersoft WebGrid RowEventArgs.</param>
	protected void wgPaymentInfoAudit_InitializeRow(object sender, ISWG.RowEventArgs e)
	{
		if (e.Row.Type == ISWG.RowType.Record &&
			e.Row.Table.Name == "PaymentInfoAuditCollection")
		{
			string PaymentInfoAuditGuidHyperlink = "PaymentInfoAuditDetail.aspx?PaymentInfoAuditGuid=" +
				e.Row.Cells.GetNamedItem("PaymentInfoAuditGuid").Value;

			// configure the column as Hyperlink
			wgPaymentInfoAudit.RootTable.Columns.GetNamedItem("AmazonToken").ColumnType =
				ISWG.ColumnType.HyperLink;

			// configure the HyperlinkFormatString
			wgPaymentInfoAudit.RootTable.Columns.GetNamedItem("AmazonToken").HyperlinkFormatString =
				PaymentInfoAuditGuidHyperlink;

			wgPaymentInfoAudit.RootTable.Columns.GetNamedItem("PaymentInfoAuditGuid").HyperlinkDisplayText =
				e.Row.Cells.GetNamedItem("AmazonToken").Text;
		}
	}
}