/*  Generated by CodeGen written by Concord Mfg.
 * Transform file used: JoinDAEntity (v0.2.0.0).xslt
 * Date generated: 3/28/2012 12:45:58 PM
 * CodeGen version: 0.2.0.0  */

using System;

namespace ConcordMfg.PremierSeniorSolutions.WebService.DataAccess
{
	/// <summary>
	/// FacilityWithCityStateZip Data Access Entity
	/// </summary>
	/// <remarks>
	/// This is the Facility class joined on cityStateZip identifier.
	/// </remarks>
	public partial class FacilityWithCityStateZip : Facility
	{
		#region Constructors
		/// <summary>
		/// Initializes a new instance of the FacilityWithCityStateZip data access entity.
		/// </summary>
		/// <remarks>This class is a facility with cityStateZip identifier.</remarks>
		public FacilityWithCityStateZip()
		{
		}
		#endregion


		#region Public Properties

		/// <summary>
		/// City State Zip Guid from CityStateZip.
		/// </summary>
		public Guid CityStateZip_CityStateZipGuid
		{
			get { return _cityStateZip_CityStateZipGuid; }
			set { _cityStateZip_CityStateZipGuid = value; }
		}

		#endregion


		#region Private Fields

		/// <summary>
		/// The CityStateZipGuid column from the CityStateZip table.
		/// </summary>
		private Guid _cityStateZip_CityStateZipGuid = Guid.Empty;

		#endregion
	}
}