/*  Generated by CodeGen written by Concord Mfg.
 *  Transform file used: BEGridControl (v0.1.0.0).xslt
 *  Date generated: 3/28/2012 12:46:29 PM
 *  CodeGen version: 0.1.0.0  */

using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using ISWG = ISNet.WebUI.WebGrid;

public partial class CityStateZip_Controls_CityStateZipGrid : System.Web.UI.UserControl
{
	private bool _needsRefresh = false;

	protected void Page_Load(object sender, EventArgs e)
	{
		wgCityStateZip.InitializePostBack += new ISWG.PostBackEventHandler(wgCityStateZip_InitializePostBack);
		wgCityStateZip.Unload += new EventHandler(wgCityStateZip_Unload);
	}

	void wgCityStateZip_InitializePostBack(object sender, ISWG.PostbackEventArgs e)
	{
		if (wgCityStateZip.ActionName == "AddRow")
		{
			_needsRefresh = true;
		}
	}

	void wgCityStateZip_Unload(object sender, EventArgs e)
	{
		if (_needsRefresh)
		{
			_needsRefresh = false;

			//isdCityStateZip.DataBind();
			//isdCityStateZip.DoSelect();
			//isdCityStateZip.Select();

			//wgCityStateZip.DataBind();
			//wgCityStateZip.GetChanges();
			//wgCityStateZip.RebindDataSource();
			//wgCityStateZip.Reset();

			// This is the current working solution. Hopefully one of the above will work instead.
			// Comment this line out to debug. The refresh hides error messages.
			this.Response.Redirect("~/CityStateZip/CityStateZipGrid.aspx");
		}
	}

	/// <summary>
	/// Builds to the link button to send the CityStateZipGuid link to the CityStateZipDetail page in the same folder.
	/// </summary>
	/// <param name="sender">Sender, as object.</param>
	/// <param name="e">Intersoft WebGrid RowEventArgs.</param>
	protected void wgCityStateZip_InitializeRow(object sender, ISWG.RowEventArgs e)
	{
		if (e.Row.Type == ISWG.RowType.Record &&
			e.Row.Table.Name == "CityStateZipCollection")
		{
			string CityStateZipGuidHyperlink = "CityStateZipDetail.aspx?CityStateZipGuid=" +
				e.Row.Cells.GetNamedItem("CityStateZipGuid").Value;

			// configure the column as Hyperlink
			wgCityStateZip.RootTable.Columns.GetNamedItem("City").ColumnType =
				ISWG.ColumnType.HyperLink;

			// configure the HyperlinkFormatString
			wgCityStateZip.RootTable.Columns.GetNamedItem("City").HyperlinkFormatString =
				CityStateZipGuidHyperlink;

			wgCityStateZip.RootTable.Columns.GetNamedItem("CityStateZipGuid").HyperlinkDisplayText =
				e.Row.Cells.GetNamedItem("City").Text;
		}
	}
}