/*  Generated by CodeGen written by Concord Mfg.
 * Transform file used: IBEGateway (v0.2.0.0).xslt
 * Date generated: 3/28/2012 12:45:59 PM
 * CodeGen version: 0.2.0.0  */

using System;
using System.Linq;

namespace ConcordMfg.PremierSeniorSolutions.WebService.DataAccess
{
	public interface IClickGateway
	{
		IOrderedQueryable<Click> GetAll();
		Click GetByPK(Guid clickGuid);
		//@@NEW - changed return type to entity type.
		Click Insert(Click entity);
		void Update(Click entity);
		void Delete(Guid clickGuid);
	}
}