/*  Generated by CodeGen written by Concord Mfg.
 * Transform file used: IBEGateway (v0.2.0.0).xslt
 * Date generated: 3/28/2012 12:45:59 PM
 * CodeGen version: 0.2.0.0  */

using System;
using System.Linq;

namespace ConcordMfg.PremierSeniorSolutions.WebService.DataAccess
{
	public interface IPaymentInfoGateway
	{
		IOrderedQueryable<PaymentInfo> GetAll();
		PaymentInfo GetByPK(Guid paymentInfoGuid);
		//@@NEW - changed return type to entity type.
		PaymentInfo Insert(PaymentInfo entity);
		void Update(PaymentInfo entity);
		void Delete(Guid paymentInfoGuid);
	}
}