/*  Generated by CodeGen written by Concord Mfg.
 *  Transform file used: BEDataContract (v0.0.6.5).xslt
 *  Date generated: 3/28/2012 12:46:07 PM
 *  CodeGen version: 0.1.0.0  */

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ConcordMfg.PremierSeniorSolutions.WebService.DataContracts
{
	/// <summary>
	/// Data Contract Class - CityStateZip
	/// </summary>
	[DataContract(Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.DataContracts/2007/01", Name = "CityStateZip")]
	public partial class CityStateZip
	{
		#region Constructors
		public CityStateZip()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the Task data contract class given its required properties.
		/// </summary>
		/// <param name="cityStateZipGuid">City State Zip Guid</param>
		/// <param name="city">City</param>
		/// <param name="state">State</param>
		/// <param name="zipCode">Zip Code</param>
		public CityStateZip(Guid cityStateZipGuid, string city, string state, string zipCode)
		{
			_cityStateZipGuid = cityStateZipGuid;
			_city = city;
			_state = state;
			_zipCode = zipCode;
		}
		#endregion


		#region Public Properties
		
		/// <summary>
		/// City State Zip Guid from CityStateZip.
		/// </summary>
		[DataMember(IsRequired = true, Name = "CityStateZipGuid", Order = 0)]
		public Guid CityStateZipGuid
		{
			get { return _cityStateZipGuid; }
			set { _cityStateZipGuid = value; }
		}
	
		/// <summary>
		/// City from CityStateZip.
		/// </summary>
		[DataMember(IsRequired = true, Name = "City", Order = 1)]
		public string City
		{
			get { return _city; }
			set { _city = value; }
		}
	
		/// <summary>
		/// State from CityStateZip.
		/// </summary>
		[DataMember(IsRequired = true, Name = "State", Order = 2)]
		public string State
		{
			get { return _state; }
			set { _state = value; }
		}
	
		/// <summary>
		/// Zip Code from CityStateZip.
		/// </summary>
		[DataMember(IsRequired = true, Name = "ZipCode", Order = 3)]
		public string ZipCode
		{
			get { return _zipCode; }
			set { _zipCode = value; }
		}
	
        #endregion


		#region Private Fields
		private Guid _cityStateZipGuid = Guid.Empty;
		private string _city = null;
		private string _state = null;
		private string _zipCode = null;
		#endregion
	}

}
	