/*  Generated by CodeGen written by Concord Mfg.
 * Transform file used: JoinDataContract (v0.1.0.0).xslt
 * Date generated: 3/28/2012 12:46:07 PM
 * CodeGen version: 0.1.0.0  */

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ConcordMfg.PremierSeniorSolutions.WebService.DataContracts
{
	/// <summary>
	/// Data Contract Class - FacilityWithCityStateZip
	/// </summary>
	[DataContract(Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.DataContracts/2007/01", Name = "FacilityWithCityStateZip")]
	public partial class FacilityWithCityStateZip
	{
		#region Constructors
		/// <summary>
		/// Initializes a new instance of the FacilityWithCityStateZip data contract class.
		/// </summary>
		public FacilityWithCityStateZip()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the FacilityWithCityStateZip data contract class given its required properties.
		/// </summary>
		/// <param name="facilityGuid">Facility Guid</param>
		/// <param name="facilityID">Facility ID</param>
		/// <param name="facilityName">Facility Name</param>
		/// <param name="exerpt">Exerpt</param>
		/// <param name="description">Description</param>
		/// <param name="address">Address</param>
		/// <param name="cityStateZipGuid">City State Zip Guid</param>
		/// <param name="phoneNumber">Phone Number</param>
		/// <param name="email">Email</param>
		/// <param name="website">Website</param>
		/// <param name="clientGuid">Client Guid</param>
		/// <param name="listingTypeGuid">Listing Type Guid</param>
		/// <param name="publicPhotoFileUri">Public Photo File Uri</param>
		/// <param name="cityStateZip_CityStateZipGuid">City State Zip Guid from CityStateZip.</param>
		public FacilityWithCityStateZip(Guid facilityGuid, int facilityID, string facilityName, string exerpt, string description, string address, Guid cityStateZipGuid, string phoneNumber, string email, string website, Guid clientGuid, Guid listingTypeGuid, string publicPhotoFileUri,
			Guid cityStateZip_CityStateZipGuid)
		{
			_facilityGuid = facilityGuid;
			_facilityID = facilityID;
			_facilityName = facilityName;
			_exerpt = exerpt;
			_description = description;
			_address = address;
			_cityStateZipGuid = cityStateZipGuid;
			_phoneNumber = phoneNumber;
			_email = email;
			_website = website;
			_clientGuid = clientGuid;
			_listingTypeGuid = listingTypeGuid;
			_publicPhotoFileUri = publicPhotoFileUri;
			_cityStateZip_CityStateZipGuid = cityStateZip_CityStateZipGuid;
		}
		#endregion


		#region Public Properties

		/// <summary>
		/// Facility Guid from Facility.
		/// </summary>
		[DataMember(IsRequired = true, Name = "FacilityGuid", Order = 0)]
		public Guid FacilityGuid
		{
			get { return _facilityGuid; }
			set { _facilityGuid = value; }
		}
	
		/// <summary>
		/// Facility ID from Facility.
		/// </summary>
		[DataMember(IsRequired = true, Name = "FacilityID", Order = 1)]
		public int FacilityID
		{
			get { return _facilityID; }
			set { _facilityID = value; }
		}
	
		/// <summary>
		/// Facility Name from Facility.
		/// </summary>
		[DataMember(IsRequired = true, Name = "FacilityName", Order = 2)]
		public string FacilityName
		{
			get { return _facilityName; }
			set { _facilityName = value; }
		}
	
		/// <summary>
		/// Exerpt from Facility.
		/// </summary>
		[DataMember(IsRequired = true, Name = "Exerpt", Order = 3)]
		public string Exerpt
		{
			get { return _exerpt; }
			set { _exerpt = value; }
		}
	
		/// <summary>
		/// Description from Facility.
		/// </summary>
		[DataMember(IsRequired = true, Name = "Description", Order = 4)]
		public string Description
		{
			get { return _description; }
			set { _description = value; }
		}
	
		/// <summary>
		/// Address from Facility.
		/// </summary>
		[DataMember(IsRequired = true, Name = "Address", Order = 5)]
		public string Address
		{
			get { return _address; }
			set { _address = value; }
		}
	
		/// <summary>
		/// City State Zip Guid from Facility.
		/// </summary>
		[DataMember(IsRequired = true, Name = "CityStateZipGuid", Order = 6)]
		public Guid CityStateZipGuid
		{
			get { return _cityStateZipGuid; }
			set { _cityStateZipGuid = value; }
		}
	
		/// <summary>
		/// Phone Number from Facility.
		/// </summary>
		[DataMember(IsRequired = true, Name = "PhoneNumber", Order = 7)]
		public string PhoneNumber
		{
			get { return _phoneNumber; }
			set { _phoneNumber = value; }
		}
	
		/// <summary>
		/// Email from Facility.
		/// </summary>
		[DataMember(IsRequired = true, Name = "Email", Order = 8)]
		public string Email
		{
			get { return _email; }
			set { _email = value; }
		}
	
		/// <summary>
		/// Website from Facility.
		/// </summary>
		[DataMember(IsRequired = true, Name = "Website", Order = 9)]
		public string Website
		{
			get { return _website; }
			set { _website = value; }
		}
	
		/// <summary>
		/// Client Guid from Facility.
		/// </summary>
		[DataMember(IsRequired = true, Name = "ClientGuid", Order = 10)]
		public Guid ClientGuid
		{
			get { return _clientGuid; }
			set { _clientGuid = value; }
		}
	
		/// <summary>
		/// Listing Type Guid from Facility.
		/// </summary>
		[DataMember(IsRequired = true, Name = "ListingTypeGuid", Order = 11)]
		public Guid ListingTypeGuid
		{
			get { return _listingTypeGuid; }
			set { _listingTypeGuid = value; }
		}
	
		/// <summary>
		/// Public Photo File Uri from Facility.
		/// </summary>
		[DataMember(IsRequired = true, Name = "PublicPhotoFileUri", Order = 12)]
		public string PublicPhotoFileUri
		{
			get { return _publicPhotoFileUri; }
			set { _publicPhotoFileUri = value; }
		}
	
		/// <summary>
		/// City State Zip Guid from CityStateZip.
		/// </summary>
		[DataMember(IsRequired = true, Name = "CityStateZip_CityStateZipGuid", Order = 14)]
		public Guid CityStateZip_CityStateZipGuid
		{
			get { return _cityStateZip_CityStateZipGuid; }
			set { _cityStateZip_CityStateZipGuid = value; }
		}

		#endregion


		#region Private Fields
		private Guid _facilityGuid = Guid.Empty;
		private int _facilityID = 0;
		private string _facilityName = null;
		private string _exerpt = null;
		private string _description = null;
		private string _address = null;
		private Guid _cityStateZipGuid = Guid.Empty;
		private string _phoneNumber = null;
		private string _email = null;
		private string _website = null;
		private Guid _clientGuid = Guid.Empty;
		private Guid _listingTypeGuid = Guid.Empty;
		private string _publicPhotoFileUri = null;
		private Guid _cityStateZip_CityStateZipGuid = Guid.Empty;
		#endregion
	}

}