/*  Generated by CodeGen written by Concord Mfg.
 *  Transform file used: BEDataContract (v0.0.6.5).xslt
 *  Date generated: 3/28/2012 12:46:07 PM
 *  CodeGen version: 0.1.0.0  */

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ConcordMfg.PremierSeniorSolutions.WebService.DataContracts
{
	/// <summary>
	/// Data Contract Class - Offering
	/// </summary>
	[DataContract(Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.DataContracts/2007/01", Name = "Offering")]
	public partial class Offering
	{
		#region Constructors
		public Offering()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the Task data contract class given its required properties.
		/// </summary>
		/// <param name="offeringGuid">Offering Guid</param>
		/// <param name="offeringID">Offering ID</param>
		/// <param name="offeringName">Offering Name</param>
		public Offering(Guid offeringGuid, int offeringID, string offeringName)
		{
			_offeringGuid = offeringGuid;
			_offeringID = offeringID;
			_offeringName = offeringName;
		}
		#endregion


		#region Public Properties
		
		/// <summary>
		/// Offering Guid from Offering.
		/// </summary>
		[DataMember(IsRequired = true, Name = "OfferingGuid", Order = 0)]
		public Guid OfferingGuid
		{
			get { return _offeringGuid; }
			set { _offeringGuid = value; }
		}
	
		/// <summary>
		/// Offering ID from Offering.
		/// </summary>
		[DataMember(IsRequired = true, Name = "OfferingID", Order = 1)]
		public int OfferingID
		{
			get { return _offeringID; }
			set { _offeringID = value; }
		}
	
		/// <summary>
		/// Offering Name from Offering.
		/// </summary>
		[DataMember(IsRequired = true, Name = "OfferingName", Order = 2)]
		public string OfferingName
		{
			get { return _offeringName; }
			set { _offeringName = value; }
		}
	
        #endregion


		#region Private Fields
		private Guid _offeringGuid = Guid.Empty;
		private int _offeringID = 0;
		private string _offeringName = null;
		#endregion
	}

}
	