/*  Generated by CodeGen written by Concord Mfg.
 * Transform file used: JoinDataContract (v0.1.0.0).xslt
 * Date generated: 3/28/2012 12:46:07 PM
 * CodeGen version: 0.1.0.0  */

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ConcordMfg.PremierSeniorSolutions.WebService.DataContracts
{
	/// <summary>
	/// Data Contract Class - OfferingWithFacility
	/// </summary>
	[DataContract(Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.DataContracts/2007/01", Name = "OfferingWithFacility")]
	public partial class OfferingWithFacility
	{
		#region Constructors
		/// <summary>
		/// Initializes a new instance of the OfferingWithFacility data contract class.
		/// </summary>
		public OfferingWithFacility()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the OfferingWithFacility data contract class given its required properties.
		/// </summary>
		/// <param name="offeringGuid">Offering Guid</param>
		/// <param name="offeringID">Offering ID</param>
		/// <param name="offeringName">Offering Name</param>
		/// <param name="facility_FacilityGuid">Facility Guid from Facility.</param>
		public OfferingWithFacility(Guid offeringGuid, int offeringID, string offeringName,
			Guid facility_FacilityGuid)
		{
			_offeringGuid = offeringGuid;
			_offeringID = offeringID;
			_offeringName = offeringName;
			_facility_FacilityGuid = facility_FacilityGuid;
		}

		/// <summary>
		/// Initializes a new instance of the OfferingWithFacility data contract class given its required properties.
		/// </summary>
		/// <param name="offeringGuid">Offering Guid</param>
		/// <param name="offeringID">Offering ID</param>
		/// <param name="offeringName">Offering Name</param>
		/// <param name="facility_FacilityGuid">Facility Guid from Facility.</param>
		/// <param name="facilityOffering_IsChecked">Is Checked from FacilityOffering.</param>
		public OfferingWithFacility(Guid offeringGuid, int offeringID, string offeringName,
			Guid facility_FacilityGuid,
			bool facilityOffering_IsChecked)
		{
			_offeringGuid = offeringGuid;
			_offeringID = offeringID;
			_offeringName = offeringName;
			_facility_FacilityGuid = facility_FacilityGuid;
			_facilityOffering_IsChecked = facilityOffering_IsChecked;
		}
		#endregion


		#region Public Properties

		/// <summary>
		/// Offering Guid from Offering.
		/// </summary>
		[DataMember(IsRequired = true, Name = "OfferingGuid", Order = 0)]
		public Guid OfferingGuid
		{
			get { return _offeringGuid; }
			set { _offeringGuid = value; }
		}
	
		/// <summary>
		/// Offering ID from Offering.
		/// </summary>
		[DataMember(IsRequired = true, Name = "OfferingID", Order = 1)]
		public int OfferingID
		{
			get { return _offeringID; }
			set { _offeringID = value; }
		}
	
		/// <summary>
		/// Offering Name from Offering.
		/// </summary>
		[DataMember(IsRequired = true, Name = "OfferingName", Order = 2)]
		public string OfferingName
		{
			get { return _offeringName; }
			set { _offeringName = value; }
		}
	
		/// <summary>
		/// Facility Guid from Facility.
		/// </summary>
		[DataMember(IsRequired = true, Name = "Facility_FacilityGuid", Order = 4)]
		public Guid Facility_FacilityGuid
		{
			get { return _facility_FacilityGuid; }
			set { _facility_FacilityGuid = value; }
		}

		/// <summary>
		/// Is Checked from FacilityOffering.
		/// </summary>
		[DataMember(IsRequired = true, Name = "FacilityOffering_IsChecked", Order = 5)]
		public bool FacilityOffering_IsChecked
		{
			get { return _facilityOffering_IsChecked; }
			set { _facilityOffering_IsChecked = value; }
		}

		#endregion


		#region Private Fields
		private Guid _offeringGuid = Guid.Empty;
		private int _offeringID = 0;
		private string _offeringName = null;
		private Guid _facility_FacilityGuid = Guid.Empty;
		private bool _facilityOffering_IsChecked = false;
		#endregion
	}

}