/*  Generated by CodeGen written by Concord Mfg.
 *  Transform file used: BEDataContract (v0.0.6.5).xslt
 *  Date generated: 3/28/2012 12:46:07 PM
 *  CodeGen version: 0.1.0.0  */

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ConcordMfg.PremierSeniorSolutions.WebService.DataContracts
{
	/// <summary>
	/// Data Contract Class - PaymentInfo
	/// </summary>
	[DataContract(Namespace = "http://ConcordMfg.PremierSeniorSolutions.WebService.DataContracts/2007/01", Name = "PaymentInfo")]
	public partial class PaymentInfo
	{
		#region Constructors
		public PaymentInfo()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the Task data contract class given its required properties.
		/// </summary>
		/// <param name="paymentInfoGuid">Payment Info Guid</param>
		/// <param name="paymentInfoID">Payment Info ID</param>
		/// <param name="amazonToken">Amazon Token</param>
		public PaymentInfo(Guid paymentInfoGuid, int paymentInfoID, string amazonToken)
		{
			_paymentInfoGuid = paymentInfoGuid;
			_paymentInfoID = paymentInfoID;
			_amazonToken = amazonToken;
		}
		#endregion


		#region Public Properties
		
		/// <summary>
		/// Payment Info Guid from PaymentInfo.
		/// </summary>
		[DataMember(IsRequired = true, Name = "PaymentInfoGuid", Order = 0)]
		public Guid PaymentInfoGuid
		{
			get { return _paymentInfoGuid; }
			set { _paymentInfoGuid = value; }
		}
	
		/// <summary>
		/// Payment Info ID from PaymentInfo.
		/// </summary>
		[DataMember(IsRequired = true, Name = "PaymentInfoID", Order = 1)]
		public int PaymentInfoID
		{
			get { return _paymentInfoID; }
			set { _paymentInfoID = value; }
		}
	
		/// <summary>
		/// Amazon Token from PaymentInfo.
		/// </summary>
		[DataMember(IsRequired = true, Name = "AmazonToken", Order = 2)]
		public string AmazonToken
		{
			get { return _amazonToken; }
			set { _amazonToken = value; }
		}
	
        #endregion


		#region Private Fields
		private Guid _paymentInfoGuid = Guid.Empty;
		private int _paymentInfoID = 0;
		private string _amazonToken = null;
		#endregion
	}

}
	