/*  Generated by CodeGen written by Concord Mfg.
 *  Transform file used: NamedBusinessEntity (v0.1.0.0).xslt
 *  Date generated: 3/28/2012 12:46:02 PM
 *  CodeGen version: 0.1.0.0  */

using System;
using System.Collections.Generic;

namespace ConcordMfg.PremierSeniorSolutions.WebService.BusinessEntities
{
    /// <summary>
    /// CityStateZip Business Entity
    /// </summary>
    public partial class CityStateZip : IComparer<CityStateZip>, IEquatable<CityStateZip>
    {
        #region Constructors
        /// <summary>
        /// Initializes a new instance of CityStateZip as a business entity.
        /// </summary>
        public CityStateZip()
        {
        }

        /// <summary>
        /// Initializes a new instance of CityStateZip as a business entity with its properties that are not auto assigned.
        /// </summary>
		/// <param name="cityStateZipGuid">City State Zip Guid</param>
		/// <param name="city">City</param>
		/// <param name="state">State</param>
		/// <param name="zipCode">Zip Code</param>
        public CityStateZip(Guid cityStateZipGuid, string city, string state, string zipCode)
        {
			_cityStateZipGuid = cityStateZipGuid;
			_city = city;
			_state = state;
			_zipCode = zipCode;
        }
        #endregion


        #region Overridden Methods
        public override string ToString()
        {
            System.Text.StringBuilder result = new System.Text.StringBuilder();

            result.AppendFormat("CityStateZipGuid: {0}. ", this.CityStateZipGuid.ToString());
            result.AppendFormat("City: {0}. ", this.City);
            result.AppendFormat("State: {0}. ", this.State);
            result.AppendFormat("ZipCode: {0}. ", this.ZipCode);

            return result.ToString();
        }
        #endregion


        #region IComparer<CityStateZip> Members

        /// <summary>
        /// Compares two CityStateZips. Compares PK and id fields separate from other fields.
        /// </summary>
        /// <param name="a">CityStateZip A</param>
        /// <param name="b">CityStateZip B</param>
        /// <returns>If the PK or ID are different, returns 1.
        /// If any other fields are different, returns -1.
        /// If all fields are identical, return 0.</returns>
        public int Compare(CityStateZip a, CityStateZip b)
        {
            if (a._cityStateZipGuid != b._cityStateZipGuid)
            { return 1; }

            if (a._city != b._city)
            { return -1; }

            if (a._state != b._state)
            { return -1; }

            if (a._zipCode != b._zipCode)
            { return -1; }

            return 0;
        }

        #endregion

        #region IEquatable

        public bool Equals(CityStateZip other)
        {
            return this._cityStateZipGuid == other._cityStateZipGuid && this._city == other._city &&
                this._state == other._state && this._zipCode == other._zipCode;
        }

        #endregion

        #region Public Properties

        /// <summary>
        /// Gets or sets the City State Zip Guid.
        /// </summary>
		public Guid CityStateZipGuid
		{
			get
			{
				return _cityStateZipGuid;
			}
			set
			{
				_cityStateZipGuid = value;
			}
		}
	
        /// <summary>
        /// Gets or sets the City.
        /// </summary>
		public string City
		{
			get { return _city; }
			set { _city = value; }
		}
	
        /// <summary>
        /// Gets or sets the State.
        /// </summary>
		public string State
		{
			get { return _state; }
			set { _state = value; }
		}
	
        /// <summary>
        /// Gets or sets the Zip Code.
        /// </summary>
		public string ZipCode
		{
			get { return _zipCode; }
			set { _zipCode = value; }
		}
	
        #endregion


        #region Private Fields

        /// <summary>
        /// The City State Zip Guid field.
        /// </summary>
		private Guid _cityStateZipGuid = Guid.Empty;

        /// <summary>
        /// The City field.
        /// </summary>
		private string _city = null;

        /// <summary>
        /// The State field.
        /// </summary>
		private string _state = null;

        /// <summary>
        /// The Zip Code field.
        /// </summary>
		private string _zipCode = null;

        #endregion

    }
  
}