/*  Generated by CodeGen written by Concord Mfg.
 *  Transform file used: NamedBusinessEntity (v0.1.0.0).xslt
 *  Date generated: 3/28/2012 12:46:02 PM
 *  CodeGen version: 0.1.0.0  */

using System;
using System.Collections.Generic;

namespace ConcordMfg.PremierSeniorSolutions.WebService.BusinessEntities
{
    /// <summary>
    /// PaymentInfoAudit Business Entity
    /// </summary>
    public partial class PaymentInfoAudit : IComparer<PaymentInfoAudit>
    {
        #region Constructors
        /// <summary>
        /// Initializes a new instance of PaymentInfoAudit as a business entity.
        /// </summary>
        public PaymentInfoAudit()
        {
        }

        /// <summary>
        /// Initializes a new instance of PaymentInfoAudit as a business entity with its properties that are not auto assigned.
        /// </summary>
		/// <param name="paymentInfoAuditGuid">Payment Info Audit Guid</param>
		/// <param name="paymentInfoGuid">Payment Info Guid</param>
		/// <param name="paymentInfoID">Payment Info ID</param>
		/// <param name="amazonToken">Amazon Token</param>
		/// <param name="dateModified">Date Modified</param>
        public PaymentInfoAudit(Guid paymentInfoAuditGuid, Guid paymentInfoGuid, int paymentInfoID, string amazonToken, DateTime dateModified)
        {
			_paymentInfoAuditGuid = paymentInfoAuditGuid;
			_paymentInfoGuid = paymentInfoGuid;
			_paymentInfoID = paymentInfoID;
			_amazonToken = amazonToken;
			_dateModified = dateModified;
        }

		//@@NEW
		public PaymentInfoAudit(PaymentInfo paymentInfo)
		{
			PaymentInfoGuid = paymentInfo.PaymentInfoGuid;
			PaymentInfoID = paymentInfo.PaymentInfoID;
			AmazonToken = paymentInfo.AmazonToken;
		}
		#endregion


        #region Overridden Methods
        public override string ToString()
        {
            System.Text.StringBuilder result = new System.Text.StringBuilder();

            result.AppendFormat("PaymentInfoAuditGuid: {0}. ", this.PaymentInfoAuditGuid.ToString());
            result.AppendFormat("PaymentInfoGuid: {0}. ", this.PaymentInfoGuid.ToString());
            result.AppendFormat("PaymentInfoID: {0}. ", this.PaymentInfoID.ToString());
            result.AppendFormat("AmazonToken: {0}. ", this.AmazonToken);
            result.AppendFormat("DateModified: {0}. ", this.DateModified.ToString());

            return result.ToString();
        }
        #endregion


        #region IComparer<PaymentInfoAudit> Members

        /// <summary>
        /// Compares two PaymentInfoAudits. Compares PK and id fields separate from other fields.
        /// </summary>
        /// <param name="a">PaymentInfoAudit A</param>
        /// <param name="b">PaymentInfoAudit B</param>
        /// <returns>If the PK or ID are different, returns 1.
        /// If any other fields are different, returns -1.
        /// If all fields are identical, return 0.</returns>
        public int Compare(PaymentInfoAudit a, PaymentInfoAudit b)
        {
            if (a._paymentInfoAuditGuid != b._paymentInfoAuditGuid)
            { return 1; }

            if (a._paymentInfoGuid != b._paymentInfoGuid)
            { return -1; }

            if (a._paymentInfoID != b._paymentInfoID)
            { return -1; }

            if (a._amazonToken != b._amazonToken)
            { return -1; }

            if (a._dateModified != b._dateModified)
            { return -1; }

            return 0;
        }

        #endregion


        #region Public Properties

        /// <summary>
        /// Gets or sets the Payment Info Audit Guid.
        /// </summary>
		public Guid PaymentInfoAuditGuid
		{
			get { return _paymentInfoAuditGuid; }
			set { _paymentInfoAuditGuid = value; }
		}
	
        /// <summary>
        /// Gets or sets the Payment Info Guid.
        /// </summary>
		public Guid PaymentInfoGuid
		{
			get { return _paymentInfoGuid; }
			set { _paymentInfoGuid = value; }
		}
	
        /// <summary>
        /// Gets or sets the Payment Info ID.
        /// </summary>
		public int PaymentInfoID
		{
			get { return _paymentInfoID; }
			set { _paymentInfoID = value; }
		}
	
        /// <summary>
        /// Gets or sets the Amazon Token.
        /// </summary>
		public string AmazonToken
		{
			get { return _amazonToken; }
			set { _amazonToken = value; }
		}
	
        /// <summary>
        /// Gets or sets the Date Modified.
        /// </summary>
		public DateTime DateModified
		{
			get { return _dateModified; }
			set { _dateModified = value; }
		}
	
        #endregion


        #region Private Fields

        /// <summary>
        /// The Payment Info Audit Guid field.
        /// </summary>
		private Guid _paymentInfoAuditGuid = Guid.Empty;

        /// <summary>
        /// The Payment Info Guid field.
        /// </summary>
		private Guid _paymentInfoGuid = Guid.Empty;

        /// <summary>
        /// The Payment Info ID field.
        /// </summary>
		private int _paymentInfoID = 0;

        /// <summary>
        /// The Amazon Token field.
        /// </summary>
		private string _amazonToken = null;

        /// <summary>
        /// The Date Modified field.
        /// </summary>
		private DateTime _dateModified = default(DateTime);

        #endregion
    }
  
}