/*  Generated by CodeGen written by Concord Mfg.
 * Transform file used: BEGateway (v0.2.0.0).xslt
 * Date generated: 3/28/2012 12:46:00 PM
 * CodeGen version: 0.2.0.0  */

using System;
using System.Configuration;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;

namespace ConcordMfg.PremierSeniorSolutions.WebService.DataAccess
{
	public class FacilityAuditGateway : GatewayBase, IFacilityAuditGateway
	{
		#region IFacilityAuditGateway Members
		public IOrderedQueryable<FacilityAudit> GetAll()
		{
			try
			{
				using (PSS2012DataContext context = this.DataContext)
				{
					return context.FacilityAudits.OrderBy(facilityAudit => facilityAudit.FacilityName);
				}
			}
			catch (System.Data.SqlClient.SqlException ex)
			{
				throw this.HandleSqlException(ex);
			}
			catch (Exception ex)
			{
				throw ex;
			}
		}

		public List<FacilityAudit> GetAllWithUndefined()
		{
			FacilityAudit undefinedFacilityAudit = new FacilityAudit()
			{
				FacilityAuditGuid = Guid.Empty,
				FacilityGuid = Guid.Empty,
				FacilityID = 0,
				FacilityName = "Undefined",
				Exerpt = null,
				Description = null,
				Address = null,
				CityStateZipGuid = Guid.Empty,
				PhoneNumber = null,
				Email = null,
				Website = null,
				ClientGuid = Guid.Empty,
				ListingTypeGuid = Guid.Empty,
				PublicPhotoFileUri = null,
				DateModified = default(DateTime),
			};

			List<FacilityAudit> response = this.GetAll().ToList();
			response.Add(undefinedFacilityAudit);

			return response;
		}

		public FacilityAudit GetByPK(Guid facilityAuditGuid)
		{
			if (Guid.Empty == facilityAuditGuid)
			{ return new FacilityAudit(); }

			try
			{
				FacilityAudit daFacilityAudit = new FacilityAudit();
				using (PSS2012DataContext context = this.DataContext)
				{
					daFacilityAudit = (
						from items in context.FacilityAudits
						where items.FacilityAuditGuid == facilityAuditGuid
						select items).SingleOrDefault();
				}

				if (null == daFacilityAudit)
				{
					throw new DataAccessException("FacilityAudit no longer exists.");
				}

				return daFacilityAudit;
			}
			catch (System.Data.SqlClient.SqlException ex)
			{
				throw this.HandleSqlException(ex);
			}
			catch (Exception ex)
			{
				throw ex;
			}
		}

		/// <summary>
		/// Inserts facilityAudit business entity into the data store.
		/// </summary>
		/// <param name="entity">The facilityAudit business entity to insert.</param>
		/// <returns>The facilityAudit identifier.</returns>
		public FacilityAudit Insert(FacilityAudit entity)
		{
			//@@NEW - changed return type to entity type.
			try
			{
				using (PSS2012DataContext context = DataContext)
				{
					entity.FacilityAuditGuid = Guid.NewGuid();
					//@@NEW
					entity.DateModified = DateTime.Now;

					context.FacilityAudits.InsertOnSubmit(entity);
					context.SubmitChanges();
				}

				//@@NEW - returning full entity.
				return entity;
			}
			catch (System.Data.SqlClient.SqlException ex)
			{
				throw this.HandleSqlException(ex);
			}
		}

		public IList<FacilityAudit> GetForFacilityByFacilityGuid(Guid facilityGuid)
		{
			try
			{
				using (PSS2012DataContext context = DataContext)
				{
					// Get the entity to delete.
					return
						(from items in context.FacilityAudits
						 where items.FacilityGuid == facilityGuid
						 select items).OrderBy(facilityAudit => facilityAudit.FacilityName).ToList();
				}
			}
			catch (System.Data.SqlClient.SqlException ex)
			{
				throw this.HandleSqlException(ex);
			}
		}

		public IOrderedQueryable<FacilityAudit> GetForCityStateZipByCityStateZipGuid(Guid cityStateZipGuid)
		{
			try
			{
				using (PSS2012DataContext context = DataContext)
				{
					// Get the entity to delete.
					return
						(from items in context.FacilityAudits
						 where items.CityStateZipGuid == cityStateZipGuid
						 select items).OrderBy(facilityAudit => facilityAudit.FacilityName);
				}
			}
			catch (System.Data.SqlClient.SqlException ex)
			{
				throw this.HandleSqlException(ex);
			}
		}

		public IOrderedQueryable<FacilityAudit> GetForClientByClientGuid(Guid clientGuid)
		{
			try
			{
				using (PSS2012DataContext context = DataContext)
				{
					// Get the entity to delete.
					return
						(from items in context.FacilityAudits
						 where items.ClientGuid == clientGuid
						 select items).OrderBy(facilityAudit => facilityAudit.FacilityName);
				}
			}
			catch (System.Data.SqlClient.SqlException ex)
			{
				throw this.HandleSqlException(ex);
			}
		}

		public IOrderedQueryable<FacilityAudit> GetForListingTypeByListingTypeGuid(Guid listingTypeGuid)
		{
			try
			{
				using (PSS2012DataContext context = DataContext)
				{
					// Get the entity to delete.
					return
						(from items in context.FacilityAudits
						 where items.ListingTypeGuid == listingTypeGuid
						 select items).OrderBy(facilityAudit => facilityAudit.FacilityName);
				}
			}
			catch (System.Data.SqlClient.SqlException ex)
			{
				throw this.HandleSqlException(ex);
			}
		}
		#endregion


		#region Private Handle Exception Methods
		private Exception HandleSqlException(System.Data.SqlClient.SqlException ex)
		{
			if (ex.Message.Contains("An error has occurred while establishing a connection to the server.  When connecting to SQL Server 2005, this failure may be caused by the fact that under the default settings SQL Server does not allow remote connections."))
			{
				return new Exception("Could not establish a connection to SQL Server. See inner exception for more details. Perhaps Windows Firewall has blocked the connection to SQL Server. Check online resources to find out how to allow port exceptions.", ex);
			}
			else if (ex.Message.Contains("Invalid object name 'dbo.FacilityAudit'"))
			{
				return new TableDoesNotExistException("PSS2012", "FacilityAudit", ex);
			}
			else if (ex.Message.Contains("Invalid column name"))
			{
				return new ColumnDoesNotExistException("PSS2012", "FacilityAudit", ex);
			}
			else if (ex.Message.Contains("String or binary data would be truncated"))
			{
				return new DataAccessException("String or number is too long or too big for the database.", ex);
			}
			else if (ex.Message.Contains("The DELETE statement conflicted with the REFERENCE constraint"))
			{
				Regex errorRx = new Regex("The DELETE statement conflicted with the REFERENCE constraint \"(?<constraint>[\\x20-\\x7E-[\"]]{1,})\". The conflict occurred in database \"(?<db>[\\x20-\\x7E-[\"]]{1,50})\", table \"dbo.(?<jtn>[\\x20-\\x7E-[\"]]{1,50})\"");
				Match errorMatch = errorRx.Match(ex.Message);
				if (errorMatch.Success)
				{
					return new RowReferencedElsewhereException(errorMatch.Groups["db"].Value, "FacilityAudit", errorMatch.Groups["jtn"].Value, ex);
				}
				else
				{ return ex; }
			}
			else
			{
				return ex;
			}
		}
		#endregion
	}
}