/*  Generated by CodeGen written by Concord Mfg.
 * Transform file used: BEGateway (v0.2.0.0).xslt
 * Date generated: 3/28/2012 12:46:00 PM
 * CodeGen version: 0.2.0.0  */

using System;
using System.Configuration;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;

namespace ConcordMfg.PremierSeniorSolutions.WebService.DataAccess
{
	public class FacilityPhotoGateway : GatewayBase, IFacilityPhotoGateway
	{
		#region IFacilityPhotoGateway Members
		public IList<FacilityPhoto> GetAll()
		{
			try
			{
				using (PSS2012DataContext context = this.DataContext)
				{
					return context.FacilityPhotos.OrderBy(facilityPhoto => facilityPhoto.PhotoUri).ToList();
				}
			}
			catch (System.Data.SqlClient.SqlException ex)
			{
				throw this.HandleSqlException(ex);
			}
		}

		public List<FacilityPhoto> GetAllWithUndefined()
		{
			FacilityPhoto undefinedFacilityPhoto = new FacilityPhoto()
			{
				FacilityPhotoGuid = Guid.Empty,
				PhotoUri = "Undefined",
				FacilityGuid = Guid.Empty,
			};

			List<FacilityPhoto> response = this.GetAll().ToList();
			response.Add(undefinedFacilityPhoto);

			return response;
		}

		public FacilityPhoto GetByPK(Guid facilityPhotoGuid)
		{
			if (Guid.Empty == facilityPhotoGuid)
			{ return new FacilityPhoto(); }

			try
			{
				FacilityPhoto daFacilityPhoto = new FacilityPhoto();
				using (PSS2012DataContext context = this.DataContext)
				{
					daFacilityPhoto = (
						from items in context.FacilityPhotos
						where items.FacilityPhotoGuid == facilityPhotoGuid
						select items).SingleOrDefault();
				}

				if (null == daFacilityPhoto)
				{
					throw new DataAccessException("FacilityPhoto no longer exists.");
				}

				return daFacilityPhoto;
			}
			catch (System.Data.SqlClient.SqlException ex)
			{
				throw this.HandleSqlException(ex);
			}
		}

		/// <summary>
		/// Inserts facilityPhoto business entity into the data store.
		/// </summary>
		/// <param name="entity">The facilityPhoto business entity to insert.</param>
		/// <returns>The facilityPhoto identifier.</returns>
		public FacilityPhoto Insert(FacilityPhoto entity)
		{
			//@@NEW - changed return type to entity type.
			try
			{
				using (PSS2012DataContext context = this.DataContext)
				{
					entity.FacilityPhotoGuid = Guid.NewGuid();

					context.FacilityPhotos.InsertOnSubmit(entity);
					context.SubmitChanges();
				}

				//@@NEW - returning full entity.
				return entity;
			}
			catch (System.Data.SqlClient.SqlException ex)
			{
				throw this.HandleSqlException(ex);
			}
		}

		public void Update(FacilityPhoto entity)
		{
			if (Guid.Empty == entity.FacilityPhotoGuid)
				throw new PrimaryKeyMissingException("FacilityPhoto", entity, "update");

			try
			{
				using (PSS2012DataContext context = this.DataContext)
				{
					// Get the entity to update.
					FacilityPhoto facilityPhotoToUpdate = GetByPK(entity.FacilityPhotoGuid);
                    context.FacilityPhotos.Attach(facilityPhotoToUpdate);
					// Set the new values.
					facilityPhotoToUpdate.PhotoUri = entity.PhotoUri;
					facilityPhotoToUpdate.FacilityGuid = entity.FacilityGuid;
                    
					// Perform the update.
					context.SubmitChanges();
				}
			}
			catch (System.Data.SqlClient.SqlException ex)
			{
				throw this.HandleSqlException(ex);
			}
		}

		public void Delete(Guid facilityPhotoGuid)
		{
			if (Guid.Empty == facilityPhotoGuid)
				throw new PrimaryKeyMissingException("FacilityPhoto", facilityPhotoGuid, "delete");

			try
			{
				using (PSS2012DataContext context = this.DataContext)
				{
					// Get the entity to delete.
					FacilityPhoto facilityPhotoToDelete = GetByPK(facilityPhotoGuid);
                    context.FacilityPhotos.Attach(facilityPhotoToDelete);
					// Peform the delete.
					context.FacilityPhotos.DeleteOnSubmit(facilityPhotoToDelete);
					context.SubmitChanges();
				}
			}
			catch (System.Data.SqlClient.SqlException ex)
			{
				throw this.HandleSqlException(ex);
			}
		}

		public IList<FacilityPhoto> GetForFacilityByFacilityGuid(Guid facilityGuid)
		{
			try
			{
				using (PSS2012DataContext context = DataContext)
				{
					// Get the entity to delete.
					return
						(from items in context.FacilityPhotos
						 where items.FacilityGuid == facilityGuid
						 select items).OrderBy(facilityPhoto => facilityPhoto.PhotoUri).ToList();
				}
			}
			catch (System.Data.SqlClient.SqlException ex)
			{
				throw this.HandleSqlException(ex);
			}
		}
		#endregion


		#region Private Handle Exception Methods
		private Exception HandleSqlException(System.Data.SqlClient.SqlException ex)
		{
			if (ex.Message.Contains("An error has occurred while establishing a connection to the server.  When connecting to SQL Server 2005, this failure may be caused by the fact that under the default settings SQL Server does not allow remote connections."))
			{
				return new Exception("Could not establish a connection to SQL Server. See inner exception for more details. Perhaps Windows Firewall has blocked the connection to SQL Server. Check online resources to find out how to allow port exceptions.", ex);
			}
			else if (ex.Message.Contains("Invalid object name 'dbo.FacilityPhoto'"))
			{
				return new TableDoesNotExistException("PSS2012", "FacilityPhoto", ex);
			}
			else if (ex.Message.Contains("Invalid column name"))
			{
				return new ColumnDoesNotExistException("PSS2012", "FacilityPhoto", ex);
			}
			else if (ex.Message.Contains("String or binary data would be truncated"))
			{
				return new DataAccessException("String or number is too long or too big for the database.", ex);
			}
			else if (ex.Message.Contains("The DELETE statement conflicted with the REFERENCE constraint"))
			{
				Regex errorRx = new Regex("The DELETE statement conflicted with the REFERENCE constraint \"(?<constraint>[\\x20-\\x7E-[\"]]{1,})\". The conflict occurred in database \"(?<db>[\\x20-\\x7E-[\"]]{1,50})\", table \"dbo.(?<jtn>[\\x20-\\x7E-[\"]]{1,50})\"");
				Match errorMatch = errorRx.Match(ex.Message);
				if (errorMatch.Success)
				{
					return new RowReferencedElsewhereException(errorMatch.Groups["db"].Value, "FacilityPhoto", errorMatch.Groups["jtn"].Value, ex);
				}
				else
				{ return ex; }
			}
			else
			{
				return ex;
			}
		}
		#endregion
	}
}