/*	Generated by CodeGen written by Concord Mfg
	*  Transform file used: JoinBusinessEntity (v0.1.0.0).xslt
	*  Date generated: 3/28/2012 12:46:17 PM
	*  CodeGen version: 0.1.0.0  */

using System;
using System.Collections;
using System.Collections.Generic;
using ISNet.WebUI.DataSource;

namespace ConcordMfg.PremierSeniorSolutions.Client.ViewModels
{
	/// <summary>
	/// The FacilityWithCityStateZip class of the web UI tier.
	/// </summary>
	public class FacilityWithCityStateZip
	{
		#region Private Fields
		private ConcordMfg.PremierSeniorSolutions.WebService.Client.FacilityWithCityStateZipSvc.FacilityWithCityStateZip _facilityWithCityStateZip = null;
		private IEnumerable _owner;
		#endregion


		#region Constructors
		/// <summary>
		/// Initializes a new instance of FacilityWithCityStateZip class for the UI tier.
		/// </summary>
		public FacilityWithCityStateZip()
		{
			_facilityWithCityStateZip = new ConcordMfg.PremierSeniorSolutions.WebService.Client.FacilityWithCityStateZipSvc.FacilityWithCityStateZip();
		}

		/// <summary>
		/// Initializes a new instance of FacilityWithCityStateZip class for the UI tier taking a proxy client object as input.
		/// </summary>
		/// <param name="facilityWithCityStateZip">FacilityWithCityStateZip proxy client object.</param>
		public FacilityWithCityStateZip(ConcordMfg.PremierSeniorSolutions.WebService.Client.FacilityWithCityStateZipSvc.FacilityWithCityStateZip facilityWithCityStateZip)
		{
			_facilityWithCityStateZip = facilityWithCityStateZip;
		}

		/// <summary>
		/// Initializes a new instance of Facility class given its properties for the UI tier.
		/// </summary>
		/// <param name="facilityGuid">Facility Guid</param>
		/// <param name="facilityID">Facility ID</param>
		/// <param name="facilityName">Facility Name</param>
		/// <param name="exerpt">Exerpt</param>
		/// <param name="description">Description</param>
		/// <param name="address">Address</param>
		/// <param name="cityStateZipGuid">City State Zip Guid</param>
		/// <param name="phoneNumber">Phone Number</param>
		/// <param name="email">Email</param>
		/// <param name="website">Website</param>
		/// <param name="clientGuid">Client Guid</param>
		/// <param name="listingTypeGuid">Listing Type Guid</param>
		/// <param name="publicPhotoFileUri">Public Photo File Uri</param>
		/// <param name="cityStateZipGuid">City State Zip Guid</param>
		public FacilityWithCityStateZip(Guid facilityGuid, int facilityID, string facilityName, string exerpt, string description, string address, Guid cityStateZipGuid, string phoneNumber, string email, string website, Guid clientGuid, Guid listingTypeGuid, string publicPhotoFileUri, Guid cityStateZipGuid)
			: this()
		{
			_facilityWithCityStateZip.FacilityGuid = facilityGuid;
			_facilityWithCityStateZip.FacilityID = facilityID;
			_facilityWithCityStateZip.FacilityName = facilityName;
			_facilityWithCityStateZip.Exerpt = exerpt;
			_facilityWithCityStateZip.Description = description;
			_facilityWithCityStateZip.Address = address;
			_facilityWithCityStateZip.CityStateZipGuid = cityStateZipGuid;
			_facilityWithCityStateZip.PhoneNumber = phoneNumber;
			_facilityWithCityStateZip.Email = email;
			_facilityWithCityStateZip.Website = website;
			_facilityWithCityStateZip.ClientGuid = clientGuid;
			_facilityWithCityStateZip.ListingTypeGuid = listingTypeGuid;
			_facilityWithCityStateZip.PublicPhotoFileUri = publicPhotoFileUri;
			_facilityWithCityStateZip.CityStateZipGuid = cityStateZipGuid;
		}
		#endregion


		#region Properties

		/// <summary>
		/// Gets and sets Facility Guid from Facility.
		/// </summary>
		[PrimaryKey()]
		[Caption("Facility Guid")]
		public Guid FacilityGuid
		{
			get { return _facilityWithCityStateZip.FacilityGuid; }
			set { _facilityWithCityStateZip.FacilityGuid = value; }
		}
		/// <summary>
		/// Gets and sets Facility ID from Facility.
		/// </summary>
		[AutoIncrement()]
		[Caption("Facility ID")]
		public int FacilityID
		{
			get { return _facilityWithCityStateZip.FacilityID; }
			set { _facilityWithCityStateZip.FacilityID = value; }
		}
		/// <summary>
		/// Gets and sets Facility Name from Facility.
		/// </summary>
		[Caption("Facility Name")]
		public string FacilityName
		{
			get { return _facilityWithCityStateZip.FacilityName; }
			set { _facilityWithCityStateZip.FacilityName = value; }
		}
		/// <summary>
		/// Gets and sets Exerpt from Facility.
		/// </summary>
		[Caption("Exerpt")]
		public string Exerpt
		{
			get { return _facilityWithCityStateZip.Exerpt; }
			set { _facilityWithCityStateZip.Exerpt = value; }
		}
		/// <summary>
		/// Gets and sets Description from Facility.
		/// </summary>
		[Caption("Description")]
		public string Description
		{
			get { return _facilityWithCityStateZip.Description; }
			set { _facilityWithCityStateZip.Description = value; }
		}
		/// <summary>
		/// Gets and sets Address from Facility.
		/// </summary>
		[Caption("Address")]
		public string Address
		{
			get { return _facilityWithCityStateZip.Address; }
			set { _facilityWithCityStateZip.Address = value; }
		}
		/// <summary>
		/// Gets and sets City State Zip Guid from Facility.
		/// </summary>
		[Caption("City State Zip Guid")]
		public Guid CityStateZipGuid
		{
			get { return _facilityWithCityStateZip.CityStateZipGuid; }
			set { _facilityWithCityStateZip.CityStateZipGuid = value; }
		}
		/// <summary>
		/// Gets and sets Phone Number from Facility.
		/// </summary>
		[Caption("Phone Number")]
		public string PhoneNumber
		{
			get { return _facilityWithCityStateZip.PhoneNumber; }
			set { _facilityWithCityStateZip.PhoneNumber = value; }
		}
		/// <summary>
		/// Gets and sets Email from Facility.
		/// </summary>
		[Caption("Email")]
		public string Email
		{
			get { return _facilityWithCityStateZip.Email; }
			set { _facilityWithCityStateZip.Email = value; }
		}
		/// <summary>
		/// Gets and sets Website from Facility.
		/// </summary>
		[Caption("Website")]
		public string Website
		{
			get { return _facilityWithCityStateZip.Website; }
			set { _facilityWithCityStateZip.Website = value; }
		}
		/// <summary>
		/// Gets and sets Client Guid from Facility.
		/// </summary>
		[Caption("Client Guid")]
		public Guid ClientGuid
		{
			get { return _facilityWithCityStateZip.ClientGuid; }
			set { _facilityWithCityStateZip.ClientGuid = value; }
		}
		/// <summary>
		/// Gets and sets Listing Type Guid from Facility.
		/// </summary>
		[Caption("Listing Type Guid")]
		public Guid ListingTypeGuid
		{
			get { return _facilityWithCityStateZip.ListingTypeGuid; }
			set { _facilityWithCityStateZip.ListingTypeGuid = value; }
		}
		/// <summary>
		/// Gets and sets Public Photo File Uri from Facility.
		/// </summary>
		[Caption("Public Photo File Uri")]
		public string PublicPhotoFileUri
		{
			get { return _facilityWithCityStateZip.PublicPhotoFileUri; }
			set { _facilityWithCityStateZip.PublicPhotoFileUri = value; }
		}
		/// <summary>
		/// Gets and sets City State Zip Guid from City State Zip.
		/// </summary>
		[Caption("City State Zip Guid")]
		public Guid CityStateZipGuid
		{
			get { return _facilityWithCityStateZip.CityStateZipGuid; }
			set { _facilityWithCityStateZip.CityStateZipGuid = value; }
		}

		/// <summary>
		/// Gets and sets the collection that  belongs to.
		/// </summary>
		internal IEnumerable Owner
		{
			get { return _owner; }
			set { _owner = value; }
		}
		#endregion


		#region Methods
		/// <summary>
		/// Updates the class.
		/// </summary>
		public void Update()
		{
		}

		/// <summary>
		/// Deletes this from the owned collection class.
		/// </summary>
		public void Delete()
		{
			FacilityWithCityStateZipCollection owner = this.Owner as FacilityWithCityStateZipCollection;
			owner.Remove(this);
		}
		#endregion
	}
}