/*	Generated by CodeGen written by Concord Mfg
 *  Transform file used: BEViewModel (v0.1.0.0).xslt
 *  Date generated: 3/28/2012 12:46:16 PM
 *  CodeGen version: 0.1.0.0  */

using System;
using System.Collections.Generic;
using ConcordMfg.PremierSeniorSolutions.Client.Models;


namespace ConcordMfg.PremierSeniorSolutions.Client.ViewModels
{
	/// <summary>
	/// View Model for Offering (Offering).
	/// </summary>
	public class OfferingViewModel : NotifyPropertyChangedBaseWithOwner
	{
		#region Private Fields
		protected Guid _offeringGuid = Guid.Empty;
		protected int _offeringID = 0;
		protected string _offeringName = null;

		private FacilityCollection _facilities = null;

		#endregion


		#region Constructors
		public OfferingViewModel()
		{
		}

		public OfferingViewModel(Guid offeringGuid, int offeringID, string offeringName)
		{
			this.OfferingGuid = offeringGuid;
			this.OfferingID = offeringID;
			this.OfferingName = offeringName;
		}
		#endregion


		#region Private GetAndSet Methods
		private void GetAndSetFacilities(Guid offeringGuid)
		{
			FacilityCollection facilities = DataAccess.GetFacilitiesForOffering(offeringGuid);
			if (null != facilities && _facilities != facilities)
			{
				_facilities = facilities;
				RaisePropertyChanged("Facilities");
			}
		}
		#endregion


		#region Public Properties

		public Guid OfferingGuid
		{
			get { return _offeringGuid; }
			set
			{
				_offeringGuid = value;
				RaisePropertyChanged("OfferingGuid");
			}
		}

		public int OfferingID
		{
			get { return _offeringID; }
			set
			{
				_offeringID = value;
				RaisePropertyChanged("OfferingID");
			}
		}

		public string OfferingName
		{
			get { return _offeringName; }
			set
			{
				_offeringName = value;
				RaisePropertyChanged("OfferingName");
			}
		}

		public FacilityCollection Facilities
		{
			get
			{
				if (null == _facilities)
				{
					try
					{
						this.GetAndSetFacilities(_offeringGuid);
					}
					catch (Exception ex)
					{
						throw ex;
					}
				}
				return _facilities;
			}
			set
			{
				if ( != value)
				{
					_facilities = value;
					RaisePropertyChanged("Facilities");
				}
			}
		}

		public string PDC
		{
			get { return this.ToString(); }
			set { ; }
		}
		#endregion


		#region Overrides
		public override string ToString()
		{
			return OfferingName;
		}
		#endregion
	}
}