/*  Generated by CodeGen written by Concord Mfg.
 *  Transform file used: BEGridControl (v0.1.0.0).xslt
 *  Date generated: 3/28/2012 12:46:29 PM
 *  CodeGen version: 0.1.0.0  */

using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using ISWG = ISNet.WebUI.WebGrid;

public partial class Client_Controls_ClientGrid : System.Web.UI.UserControl
{
	private bool _needsRefresh = false;

	protected void Page_Load(object sender, EventArgs e)
	{
		wgClient.InitializePostBack += new ISWG.PostBackEventHandler(wgClient_InitializePostBack);
		wgClient.Unload += new EventHandler(wgClient_Unload);
	}

	void wgClient_InitializePostBack(object sender, ISWG.PostbackEventArgs e)
	{
		if (wgClient.ActionName == "AddRow")
		{
			_needsRefresh = true;
		}
	}

	void wgClient_Unload(object sender, EventArgs e)
	{
		if (_needsRefresh)
		{
			_needsRefresh = false;

			//isdClient.DataBind();
			//isdClient.DoSelect();
			//isdClient.Select();

			//wgClient.DataBind();
			//wgClient.GetChanges();
			//wgClient.RebindDataSource();
			//wgClient.Reset();

			// This is the current working solution. Hopefully one of the above will work instead.
			// Comment this line out to debug. The refresh hides error messages.
			this.Response.Redirect("~/Client/ClientGrid.aspx");
		}
	}

	/// <summary>
	/// Builds to the link button to send the ClientGuid link to the ClientDetail page in the same folder.
	/// </summary>
	/// <param name="sender">Sender, as object.</param>
	/// <param name="e">Intersoft WebGrid RowEventArgs.</param>
	protected void wgClient_InitializeRow(object sender, ISWG.RowEventArgs e)
	{
		if (e.Row.Type == ISWG.RowType.Record &&
			e.Row.Table.Name == "ClientCollection")
		{
			string ClientGuidHyperlink = "ClientDetail.aspx?ClientGuid=" +
				e.Row.Cells.GetNamedItem("ClientGuid").Value;

			// configure the column as Hyperlink
			wgClient.RootTable.Columns.GetNamedItem("ClientName").ColumnType =
				ISWG.ColumnType.HyperLink;

			// configure the HyperlinkFormatString
			wgClient.RootTable.Columns.GetNamedItem("ClientName").HyperlinkFormatString =
				ClientGuidHyperlink;

			wgClient.RootTable.Columns.GetNamedItem("ClientGuid").HyperlinkDisplayText =
				e.Row.Cells.GetNamedItem("ClientName").Text;
		}
	}
}