/*  Generated by CodeGen written by Concord Mfg.
 *  Transform file used: BEGridControl (v0.1.0.0).xslt
 *  Date generated: 3/28/2012 12:46:29 PM
 *  CodeGen version: 0.1.0.0  */

using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using ISWG = ISNet.WebUI.WebGrid;

public partial class ListingType_Controls_ListingTypeGrid : System.Web.UI.UserControl
{
	private bool _needsRefresh = false;

	protected void Page_Load(object sender, EventArgs e)
	{
		wgListingType.InitializePostBack += new ISWG.PostBackEventHandler(wgListingType_InitializePostBack);
		wgListingType.Unload += new EventHandler(wgListingType_Unload);
	}

	void wgListingType_InitializePostBack(object sender, ISWG.PostbackEventArgs e)
	{
		if (wgListingType.ActionName == "AddRow")
		{
			_needsRefresh = true;
		}
	}

	void wgListingType_Unload(object sender, EventArgs e)
	{
		if (_needsRefresh)
		{
			_needsRefresh = false;

			//isdListingType.DataBind();
			//isdListingType.DoSelect();
			//isdListingType.Select();

			//wgListingType.DataBind();
			//wgListingType.GetChanges();
			//wgListingType.RebindDataSource();
			//wgListingType.Reset();

			// This is the current working solution. Hopefully one of the above will work instead.
			// Comment this line out to debug. The refresh hides error messages.
			this.Response.Redirect("~/ListingType/ListingTypeGrid.aspx");
		}
	}

	/// <summary>
	/// Builds to the link button to send the ListingTypeGuid link to the ListingTypeDetail page in the same folder.
	/// </summary>
	/// <param name="sender">Sender, as object.</param>
	/// <param name="e">Intersoft WebGrid RowEventArgs.</param>
	protected void wgListingType_InitializeRow(object sender, ISWG.RowEventArgs e)
	{
		if (e.Row.Type == ISWG.RowType.Record &&
			e.Row.Table.Name == "ListingTypeCollection")
		{
			string ListingTypeGuidHyperlink = "ListingTypeDetail.aspx?ListingTypeGuid=" +
				e.Row.Cells.GetNamedItem("ListingTypeGuid").Value;

			// configure the column as Hyperlink
			wgListingType.RootTable.Columns.GetNamedItem("ListingTypeName").ColumnType =
				ISWG.ColumnType.HyperLink;

			// configure the HyperlinkFormatString
			wgListingType.RootTable.Columns.GetNamedItem("ListingTypeName").HyperlinkFormatString =
				ListingTypeGuidHyperlink;

			wgListingType.RootTable.Columns.GetNamedItem("ListingTypeGuid").HyperlinkDisplayText =
				e.Row.Cells.GetNamedItem("ListingTypeName").Text;
		}
	}
}